### ISSUE TITLE
Control PWM Heater Outputs - LEDs

### ISSUE THREAD

**Issue by MonsterMuffin** [marcolivierarsenault/moonraker-home-assistant#114]
## Is your feature request related to a problem? Please describe.

I would like to be able to control my chamber lighting through HASS.

## Describe your setup

I have chamber lighting that is controlled via PWM on a 24v heater output. The config for this is [here.](https://github.com/MonsterMuffin/voron_2.4_klipper/blob/main/config/extras/daylight.cfg)

```
[output_pin daylight]
pin: PB11 #HE3
pwm: True
cycle_time: 0.01
```

This is controllable via the Mainsail UI (0.0 > 1, shown in the UI as 0% - 100%).

## Describe the solution you'd like

It would be nice for this to be exposed to HASS and ideally have control over the brightness and not just on/off, currently, this is not picked up by the integration at all. 

Cheers :)

**Comment by cashew22** [comment]
@MonsterMuffin Just letting you know that I started to look at this. The only issue I have so far is from the point of view of Moonraker, I can't know if the pin is digital or a PWM, once I figure this out it should be easy

**Comment by MonsterMuffin** [comment]
@cashew22 Just wanted to let you know that this works perfectly in the latest update. Thank you!

**Comment by cashew22** [comment]
@MonsterMuffin Glad the hear it :)
