### ISSUE TITLE
RPI/Host Shutdown Switch/Button

### ISSUE THREAD

**Issue by 0St0n30** [marcolivierarsenault/moonraker-home-assistant#129]
Hello, can you please add an option to shutdown the RPI via HA? 
Thanks

**Comment by marcolivierarsenault** [comment]
Should be straight forward, will add in next release

**Comment by 0St0n30** [comment]
Thank you very much!

**Comment by 0St0n30** [comment]
Thank you very much!

**Comment by marcolivierarsenault** [comment]
Update the code, it will be live in the next release. 
In the mean time if you want it, you can use the latest code.

https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html#download-the-latest-version-of-the-code

**Comment by 0St0n30** [comment]
thank you very much, what is the command?

**Comment by 0St0n30** [comment]
Thank you very much!

**Comment by 0St0n30** [comment]
Thank you very much!
