### ISSUE TITLE
[Feature Request] Host MCU Option for sensors etc 

### ISSUE THREAD

**Issue by qwasy** [marcolivierarsenault/moonraker-home-assistant#130]
Hi

I'm using the following part in my config to get values from a DS18b20 sensor. It is attached to the GPIO Pins of a RPi 3.
The Pi itself is a secondary MCU Host for klipper. https://www.klipper3d.org/RPi_microcontroller.html

The config part is:

[mcu host]
serial:  /tmp/klipper_host_mcu

[temperature_sensor enclosure]
sensor_type: DS18B20
serial_no: 28-00000c8b776e
sensor_mcu: host

Would it be possible to get that data aswell?
Maybe like an option field where variables can be defined.

At the moment, im using the moonraker url query, and add a "&temperature_sensor%20enclosure" at the end.
(The whole thing is: resource: "http://192.168.1.10:7125/printer/objects/query?heater_bed&extruder&print_stats&toolhead&display_status&virtual_sdcard&temperature_sensor%20enclosure")

Thanks :D

**Comment by cashew22** [comment]
@qwasy Do you use the latest version of the integration? I don't see any reason why this would not already work. If it does not can you provide debug logs ?

**Comment by qwasy** [comment]
Oh damn, you're right :D
I don't remember which version I started with, but the enclosure sensor wasn't there.
Now it is. Awesome :)
( I think I forgot to update my sensor list in HA, that's why I didn't saw it)
