### ISSUE TITLE
Webcam does not work in HA

### ISSUE THREAD

**Issue by nelsongraca** [marcolivierarsenault/moonraker-home-assistant#136]
## Version of the moonraker integration
0.9.0

## Describe your setup

MJPEG-Streamer, Klipper, Moonraker and Mainsail all running on containers, Home Assistant as well but with host network.
Webcam works in Mainsail.

The hostname resolves inside the home-assistant container and on the host.

## Describe the bug

Everything works properly in the integration except the webcam

I get the following error on HomeAssistant when trying to view the webcam
ERROR (MainThread) [homeassistant.components.mjpeg] Error getting new camera image from Flow Main: Cannot connect to host HOSTNAME_REDACTED http:80 ssl:default [Name does not resolve]

## Moonraker Logs

See message above

**Comment by marcolivierarsenault** [comment]
@nelsongraca can you tell me what this gives you:
http://URL_OF_YOUR_MOONRAKER/server/webcams/list

**Comment by nelsongraca** [comment]
Sure:

  {
     "result":{
        "webcams":[
           {
              "enabled":true,
              "icon":"M12,2A7,7 0 0,1 19,9A7,7 0 0,1 12,16A7,7 0 0,1 5,9A7,7 0 0,1 12,2M12,4A5,5 0 0,0 7,9A5,5 0 0,0 12,14A5,5 0 0,0 17,9A5,5 0 0,0 12,4M12,6A3,3 0 0,1 15,9A3,3 0 0,1 12,12A3,3 0 0,1 9,9A3,3 0 0,1 12,6M6,22A2,2 0 0,1 4,20C4,19.62 4.1,19.27 4.29,18.97L6.11,15.81C7.69,17.17 9.75,18 12,18C14.25,18 16.31,17.17 17.89,15.81L19.71,18.97C19.9,19.27 20,19.62 20,20A2,2 0 0,1 18,22H6Z",
              "aspect_ratio":"4:3",
              "target_fps_idle":5,
              "name":"Main",
              "location":"printer",
              "service":"mjpegstreamer-adaptive",
              "target_fps":15,
              "stream_url":"http://IP_ADDRESS?action=stream",
              "snapshot_url":"http://IP_ADDRESS?action=snapshot",
              "flip_horizontal":false,
              "flip_vertical":false,
              "rotation":0,
              "source":"database",
              "extra_data":{
                 
              }
           }
        ]
     }
  }

**Comment by nelsongraca** [comment]
Yes I do.

**Comment by marcolivierarsenault** [comment]
Aaa ok thats why. 

Ok let me fix that over the next week or so.

**Comment by marcolivierarsenault** [comment]
@nelsongraca What is your comfort level with GIT? 
Could you test a branch in your setup. I can't do it because I don't have the same setup and my webcam does not generate similar links

If so could you test the PR #157

**Comment by nelsongraca** [comment]
My comfort level with git is daily use with some long and fun rebases so
don't worry about it.
I'll try to test it in the next few days and let you know how it goes.

**Comment by marcolivierarsenault** [comment]
Haha perfect.

Sadly you should not have too much complications here 😂.

(Maybe some conflicts with your layer section manual code)


-- 
Marc-Olivier Arsenault

**Comment by nelsongraca** [comment]
Just tested no git issues to report as I simply downloaded the changed file :D

Camera is now working, merge away.
