### ISSUE TITLE
current_layer is wrong

### ISSUE THREAD

**Issue by nelsongraca** [marcolivierarsenault/moonraker-home-assistant#137]
## Version of the moonraker integration
0.9.0

## Describe the bug

Current layer says 6 when moonraker says 1.

I have done a light reading on the code and it is calculating the layer, I have that information being correctly set with `SET_PRINT_STATS_INFO` that sets the information on the print_stats.info object exposed by mooraker.
partial example below

    {
       "result":{
          "status":{
             "print_stats":{
                "info":{
                   "total_layer":132,
                   "current_layer":1
                }
             },
             "eventtime":1057200.052048971
          }
       }
    }

**Comment by nelsongraca** [comment]
adding this before the current return in `calculate_current_layer` 

    if (data["status"]["print_stats"]["info"]["current_layer"] != null):
        return data["status"]["print_stats"]["info"]["current_layer"]

gives me the correct info

**Comment by marcolivierarsenault** [comment]
@nelsongraca we will look at fixing it in the next few weeks, that being said, if you have bandwith, feel free to propose a PR

**Comment by nelsongraca** [comment]
@marcolivierarsenault I'll try to, since I have the code working should be quick, but I want to add an alternative way for the total layer count as well, it's contained in the same object that reports the current layer

**Comment by marcolivierarsenault** [comment]
@nelsongraca any chance with this?

**Comment by nelsongraca** [comment]
Creating the PR right now.

**Comment by nelsongraca** [comment]
Done: https://github.com/marcolivierarsenault/moonraker-home-assistant/pull/156

This has been running on my instance for a while and works
