### ISSUE TITLE
camera entity state "idle" when printer is off

### ISSUE THREAD

**Issue by marcinbauer85** [marcolivierarsenault/moonraker-home-assistant#139]
## Version of the moonraker integration
0.9.0
## Describe your setup

Klipper+Mainsail running on RPIZero with CR10S-Pro

## Describe the bug

The camera entity in the integration is always reporting "idle" status even if the printer (and the RPIZero) is off.

## Moonraker Logs

**Comment by marcolivierarsenault** [comment]
What would you expect to get as a value?

**Comment by marcolivierarsenault** [comment]
@marcinbauer85 What would you expect to get as a value?
