### ISSUE TITLE
No camera entity created

### ISSUE THREAD

**Issue by boehser-enkel** [marcolivierarsenault/moonraker-home-assistant#143]
## Version of the moonraker integration

newest

## Describe your setup

RPI with Moonraker & Mainsail in Docker container
HA 2023.6

## Describe the bug

Every entity is created within HA except the camera

## Moonraker Logs
Local webcam configured in Mainsail /webcam/?action=stream

HA: 

 Logger: py.warnings
Source: components/camera/img_util.py:64
First occurred: 09:37:10 (30 occurrences)
Last logged: 09:51:20

    /usr/local/lib/python3.11/site-packages/turbojpeg.py:880: UserWarning: Corrupt JPEG data: 7149 extraneous bytes before marker 0xd9 warnings.warn(self.__get_error_string(handle))
    /usr/local/lib/python3.11/site-packages/turbojpeg.py:880: UserWarning: Corrupt JPEG data: 7122 extraneous bytes before marker 0xd9 warnings.warn(self.__get_error_string(handle))
    /usr/local/lib/python3.11/site-packages/turbojpeg.py:880: UserWarning: Corrupt JPEG data: 6604 extraneous bytes before marker 0xd9 warnings.warn(self.__get_error_string(handle))
    /usr/local/lib/python3.11/site-packages/turbojpeg.py:880: UserWarning: Corrupt JPEG data: 6536 extraneous bytes before marker 0xd9 warnings.warn(self.__get_error_string(handle))
    /usr/local/lib/python3.11/site-packages/turbojpeg.py:880: UserWarning: Corrupt JPEG data: 6602 extraneous bytes before marker 0xd9 warnings.warn(self.__get_error_string(handle))

**Comment by marcolivierarsenault** [comment]
@boehser-enkel 

When you open your browser and do

http://MOONRAKER_URL/webcam/?action=stream

do you have the cam image?

**Comment by boehser-enkel** [comment]
> @boehser-enkel
> 
> When you open your browser and do
> 
> http://MOONRAKER_URL/webcam/?action=stream
> 
> do you have the cam image?

Yes I do

**Comment by boehser-enkel** [comment]
Nothing changed but no I see the camera
