### ISSUE TITLE
Not all Fans available in HA

### ISSUE THREAD

**Issue by claudermilk** [marcolivierarsenault/moonraker-home-assistant#147]
## Version of the moonraker integration
 0.9.0

## Describe your setup
Home Assistant Yellow  2023.6.2

Voron Trident, BTT Octopus & RPi 4B
Running Klipper v0.11.0-180-g011b4e39, Moonraker v0.8.0-35-geff0901, Mainsail v2.5.1 or Fluidd v1.24.0.
Yes, Klipper and Moonraker are a version or two old. That is deliberate due to the current bug in the latest version breaking USB; the printer works fine so I'm not opening that can of worms.

Fan configs for missing entities are:
[temperature_fan chamber]
pin: PD13
max_power: 1.0
shutdown_speed: 0.0
cycle_time: 0.0005     #2 kHz PWM signal
hardware_pwm: False
kick_start_time: 0
sensor_type: Generic 3950
sensor_pin: PF5
min_temp: 0
max_temp: 70
target_temp: 0
max_speed: 1.0 #0.7
min_speed: 0.1
control: pid
pid_Kp: 2.0     ;40
pid_Ki: 5.0     ;0.2
pid_Kd: 0.5     ;0.1
pid_deriv_time: 2.0
gcode_id: C

[fan_generic nevermore_fan]
## Nevermore - FAN4 on Octopus
pin: PD14

## Describe the bug
I can see the hotend and parts fans. I cannot see my chamber exhaust or generic Nevermore fans as entities in Home Assistant.

## Moonraker Logs
Not sure what log would help. I don't see any messages or errors for the integration.

**Comment by marcolivierarsenault** [comment]
Do you see them in Mainsail or Fluid?

Can you query (in your browser) http://YOUR_URL/printer/objects/list
and show the output. Is the Fan you are looking for in it.

**Comment by Martorias** [comment]
> Do you see them in Mainsail or Fluid?
> 
> Can you query (in your browser) http://YOUR_URL/printer/objects/list and show the output. Is the Fan you are looking for in it.

Not op but I have the same issue and using your url I can see my extra fans there (generic Bed_Fans and exhaust fan).

My exhaust fan was there at the start actually, but not since I moved it to a separate cfg file. Gonna try move it.

**Comment by marcolivierarsenault** [comment]
if you can show me the output of the URL it would help a lot.

**Comment by claudermilk** [comment]
Yes, they have always shown in Mainsail and Fluidd. I grabbed the JSON from that URL and all the fans are in the objects data. THe missing ones in HA is my temperature_fan chamber and fan_generic evermore_fan.  Here's the raw output:
{"result": {"objects": ["webhooks", "configfile", "mcu", "mcu rpi", "gcode_move", "print_stats", "virtual_sdcard", "pause_resume", "display_status", "gcode_macro CANCEL_PRINT", "gcode_macro PAUSE", "gcode_macro RESUME", "gcode_macro _TOOLHEAD_PARK_PAUSE_CANCEL", "fan", "heaters", "heater_fan hotend_fan", "fan_generic controller_fan", "temperature_fan chamber", "fan_generic nevermore_fan", "gcode_macro M141", "gcode_macro VENT", "gcode_macro _VENT_INFO", "gcode_macro _EXECUTE_AT_INIT", "gcode_macro _USER_VARIABLE", "neopixel caselight", "neopixel sb_leds", "gcode_macro led_busy", "gcode_macro led_calibrating_z", "gcode_macro led_cleaning", "gcode_macro led_blinkenlights", "gcode_macro led_heating", "gcode_macro led_toolhead_heating", "gcode_macro led_homing", "gcode_macro led_input_shaper", "gcode_macro led_leveling", "gcode_macro led_loading", "gcode_macro led_meshing", "gcode_macro led_case_off", "gcode_macro led_off", "gcode_macro led_party_time", "gcode_macro led_printing", "gcode_macro led_probe_calibrate", "gcode_macro led_purge", "gcode_macro led_filament_runout", "gcode_macro led_standby", "gcode_macro led_unloading", "save_variables", "gcode_macro PRINT_START", "gcode_macro PRINT_END", "gcode_macro PARK", "gcode_macro G28", "gcode_macro _CG28", "gcode_macro M73", "gcode_macro _HEATSOAK", "gcode_macro PREHEAT", "gcode_macro PROBE_CALIBRATE", "bed_mesh", "gcode_macro TEST_SPEED", "gcode_macro BED_MESH_CALIBRATE", "gcode_macro Z_TILT_ADJUST", "gcode_macro SETUP_KAMP_MESHING", "gcode_macro LINE_PURGE", "gcode_macro SETUP_LINE_PURGE", "gcode_macro MESH_CONFIG", "gcode_macro VORON_PURGE", "gcode_macro SETUP_VORON_PURGE", "gcode_macro DUMP_PARAMETER", "gcode_macro DUMP_PRINT_AREA_LIMITS", "gcode_macro _FILAMENT_BALL", "gcode_macro LOAD_FILAMENT", "gcode_macro UNLOAD_FILAMENT", "gcode_macro ADD_FILAMENT", "gcode_macro REMOVE_FILAMENT", "gcode_macro LIST_FILAMENTS", "gcode_macro SET_FILAMENT", "gcode_macro PRIME_LINE", "gcode_macro _SET_PLATE_OFFSET", "gcode_macro LIST_PLATES", "gcode_macro SET_PLATE", "gcode_macro ADD_PLATE", "gcode_macro REMOVE_PLATE", "gcode_macro CHANGE_PLATE_VALUE", "gcode_macro clean_nozzle", "gcode_macro _WIPE", "filament_switch_sensor runout", "gcode_macro M600", "gcode_macro GET_TIMELAPSE_SETUP", "gcode_macro _SET_TIMELAPSE_SETUP", "gcode_macro TIMELAPSE_TAKE_FRAME", "gcode_macro _TIMELAPSE_NEW_FRAME", "gcode_macro HYPERLAPSE", "gcode_macro TIMELAPSE_RENDER", "gcode_macro TEST_STREAM_DELAY", "gcode_macro BACKUP_CFG", "gcode_macro STOP_WEBCAM", "gcode_macro START_WEBCAM", "gcode_macro REFRESH_OBICO", "gcode_macro RESONANCES_TEST", "gcode_macro MEASURE_COREXY_BELT_TENSION", "gcode_macro TEST_PROBE_ACCURACY", "exclude_object", "stepper_enable", "tmc2209 stepper_x", "tmc2209 stepper_y", "tmc2209 stepper_z", "tmc2209 stepper_z1", "tmc2209 stepper_z2", "tmc2209 extruder", "heater_bed", "probe", "idle_timeout", "z_tilt", "temperature_host pi_4_mcu", "temperature_sensor pi_4_mcu", "temperature_sensor octopus_mcu", "motion_report", "query_endstops", "system_stats", "manual_probe", "toolhead", "extruder"]}}

**Comment by marcolivierarsenault** [comment]
and which is the fan you want but don't see

**Comment by marcolivierarsenault** [comment]
@cashew22 any reason we only filter for those: https://github.com/marcolivierarsenault/moonraker-home-assistant/blob/main/custom_components/moonraker/sensor.py#L338C5-L338C48

**Comment by Martorias** [comment]
{"result": {"objects": ["webhooks", "configfile", "mcu", "mcu rpi", "gcode_move", "print_stats", "virtual_sdcard", "pause_resume", "display_status", "gcode_macro CANCEL_PRINT", "gcode_macro status_printing", "exclude_object", "heaters", "temperature_sensor chamber", "temperature_host raspberry_pi", "temperature_sensor raspberry_pi", "temperature_sensor mcu_temp", "bed_mesh", "fan_generic BedFans", "fan_generic exhaust_fan", "gcode_macro BEDFANSSLOW", "tmc2209 extruder", "heater_bed", "probe", "fan", "heater_fan hotend_fan", "idle_timeout", "quad_gantry_level", "output_pin beeper", "menu", "neopixel btt_mini12864", "gcode_macro PARK", "gcode_macro G32", "motion_report", "query_endstops", "system_stats", "manual_probe", "toolhead", "extruder"]}}

I removed some macros etc to shorten it, but the ones I miss are the fan_generic exhaust_fan and BedFans.
I tried moving one to the printer.cfg instead but no difference. Also tried removing the device and uninstalling, restarting and re-installing.

**Comment by marcolivierarsenault** [comment]
Looks we could add: `temperature_fan` and `fan_generic`

**Comment by Martorias** [comment]
> Looks we could add: `temperature_fan` and `fan_generic`

I tried adding fan_generic and reloading and they both showed up for me :-)

**Comment by marcolivierarsenault** [comment]
@Martorias I updated the code, will create a release after fixing couple of bugs. In the mean time, [you can download latest code](https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html). Select `main`

**Comment by claudermilk** [comment]
I downloaded the main branch and restarted. I still don't see the two missing fans.  temperature_fan chamber and fan_generic nevermore_fan.

**Comment by marcolivierarsenault** [comment]
@claudermilk 
1) Can you validate on which version of the code you are. https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html
1) `temperature_fan` will never show up as a fan since it is a temperature sensor, you should be able to see it in the temperature section
1) Can you give me your debug logs. Ideally do this https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log  (Make sure to restart it)

**Comment by claudermilk** [comment]
Ok, now it's showing the Nevermore fan.
1. I had told HACS to load the main branch, but it was still stuck on 0.9.0. Two more tries and now it shows 9920be5.
2. < facepalm > ID10T error. Yes, I have the chamber temp showing. Never mind this.
3. I do have the debug log if you still need it, but I think that's moot now.
