### ISSUE TITLE
Change Port Number

### ISSUE THREAD

**Issue by yurbd** [marcolivierarsenault/moonraker-home-assistant#15]
Hi, i use my printer at port 7127, but the extension only accepts 7125, how can i change?

**Comment by marcolivierarsenault** [comment]
I will work on a fix, might need your help to test

**Comment by ripple7511** [comment]
I'm also one to leverage a different port than 7125. Happy to test as well.

**Comment by marcolivierarsenault** [comment]
Thanks folks, we will be implementing this feature in the next few days

**Comment by cashew22** [comment]
Closing the issue, it will be available in 0.3.0
