### ISSUE TITLE
Missing data on some entities (ETA, Time Left, and Duration) while printing

### ISSUE THREAD

**Issue by spikeygg** [marcolivierarsenault/moonraker-home-assistant#158]
## Version of the moonraker integration
Moonraker API version V0.9.1 (installed with HACS)

## Describe your setup
I am using a Voron printer with Klipper v0.11.0-205-g5f0d252b
It's running on a raspberry pi4, hosting fluidd and mainsail simultaneously with kiauh.

## Describe the bug
When printing I see many of the sensors populate with good data but there are a few, namely:

1. Voron Print ETA
2. Voron Print Time Left
3. Voron print Projected Total Duration

which do not populate, here's an example image I took while printing:
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1015891/fc6c8b1e-0898-42d3-9005-59b3156d6f02)

## Moonraker Logs
[moonraker.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/11997727/moonraker.log)

**Comment by marcolivierarsenault** [comment]
Hey couple of questions.

Can you get [HomeAssistant debug logs](https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log) then start a print wait 2-3 minutes and then download the logs. 

Also while printing, could you get the content of http://YOUR_MOONRAKER_IP/printer/objects/query?print_stats

**Comment by spikeygg** [comment]
Sure thing! Here's the moonraker stats:
```
{
"result": {
"status": {
"print_stats": {
"info": {
"total_layer": null,
"current_layer": null
},
"print_duration": 118.89106422598707,
"total_duration": 127.99193990597269,
"filament_used": 243.4393399999998,
"filename": "Shape-Cylinder.gcode",
"state": "printing",
"message": ""
}
},
"eventtime": 507447.796268482
}
}
```

Here's the debug log:
[home-assistant_moonraker_2023-07-11T01-28-43.463Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/12009801/home-assistant_moonraker_2023-07-11T01-28-43.463Z.log)

**Comment by spikeygg** [comment]
Wait a tick, I just googled around for those `null` values and I found this: https://moonraker.readthedocs.io/en/latest/printer_objects/ Print Stats section that says:

> info: This is a dict containing information about the print provided by the slicer. Currently this is limited to the total_layer and current_layer values. Note that these values are set by the [SET_PRINT_STATS_INFO](https://www.klipper3d.org/G-Codes.html#set_print_stats_info) gcode command. It is necessary to configure the slicer to include this command in the print. SET_PRINT_STATS_INFO TOTAL_LAYER=total_layer_count should be called in the slicer's "start gcode" to initalize the total layer count. SET_PRINT_STATS_INFO CURRENT_LAYER=current_layer should be called in the slicer's "on layer change" gcode. The user must substitute the total_layer_count and current_layer with the appropriate "placeholder syntax" for the slicer.

I'm going to try this and see if I can get those to populate.

**Comment by marcolivierarsenault** [comment]
Did this log was made during printing??

Could you make sure to start the debugging log before, then start your print, let it run for a while, then stop log.

Also make sure to update integration

**Comment by spikeygg** [comment]
The previous log was generated during printing but it appears to have included a bunch of other logging detail as well. I am running V0.9.2 version of the Moonraker HACS integration.

I just tried it again. The process I used was:

1. Turn on debug logging in the moonraker integration
2. Wait about 5-10 minutes, start the print
3. Wait for the print to end (~20 minutes)
4. Wait another 5-10 minutes, stop debug logging and download the log file (attached).

[home-assistant_moonraker_2023-07-23T15-14-14.858Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/12139005/home-assistant_moonraker_2023-07-23T15-14-14.858Z.log)

Something I noticed was that the "Voron Print Time Left" showed a negative number in the chart but `0` on the entities view card:

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1015891/81513c60-6f71-48d0-ac4b-bbd3f78b9c73)

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1015891/76a46b69-ff81-46fd-a1b7-d038ac24ef57)

When I look at a print that I did yesterday it appears to be subtracting the print time from zero, as it eventually gets very negative at the end of the print:
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1015891/2641eda6-5081-4da9-a359-f92bf05d68e2)
for this print, about -1000s, this print took roughly 15 minutes which is about 1000s.

**Comment by marcolivierarsenault** [comment]
Looks like we are failing to get the metadata from the gcode file:
```
2023-07-23 08:45:55.616 ERROR (MainThread) [custom_components.moonraker] failed to get thumbnails  {'thumbnails'}
2023-07-23 08:45:55.617 ERROR (MainThread) [custom_components.moonraker] Query Object {{'filename': 'DJI O3 VTX Mount - 0s 16m.gcode'}}
2023-07-23 08:45:55.617 ERROR (MainThread) [custom_components.moonraker] gcode {{'error': {'code': -32601, 'message': 'Metadata not available for <DJI O3 VTX Mount - 0s 16m.gcode>'}}}
```

I am trying to figure out what is not working on my side 

In the mean time can you try to query 
`http://YOUR_MOONRAKER_IP/server/files/metadata?filename=DJI%20O3%20VTX%20Mount%20-%200s%2016m.gcode`
or
`http://YOUR_MOONRAKER_IP/server/files/metadata?filename=DJI O3 VTX 0Mount - 0s 16m.gcode`


First time we get this error

**Comment by spikeygg** [comment]
Okay, turns out I deleted the gcode for that earlier today but I tried it on another file that does still exist and also showed the problem.

URL I used was: http://voron/server/files/metadata?filename=Can%20Plug%20-%200s%2018m.gcode

```
{
"result": {
"size": 534492,
"modified": 1690123592.8204348,
"uuid": "03463233-dcfc-4ef8-9559-f78280fa3a44",
"slicer": "PrusaSlicer",
"slicer_version": "2.6.0+win64",
"gcode_start_byte": 37900,
"gcode_end_byte": 519794,
"layer_count": 12,
"object_height": 2.45,
"estimated_time": 1108,
"nozzle_diameter": 0.4,
"layer_height": 0.2,
"first_layer_height": 0.25,
"first_layer_extr_temp": 245,
"first_layer_bed_temp": 110,
"filament_name": "KVP - ABS\";\"KVP - ABS\";\"KVP - ABS\";\"KVP - ABS\";\"KVP - ABS\";\"KVP - ABS\";\"KVP - ABS\";\"Polymaker - ABS\";\"KVP - ABS",
"filament_type": "ABS;ABS;ABS;ABS;ABS;ABS;ABS;ASA;ABS",
"filament_total": 0,
"filament_weight_total": 7.37,
"thumbnails": [
{
"width": 32,
"height": 24,
"size": 1380,
"relative_path": ".thumbs/Can Plug - 0s 18m-32x32.png"
},
{
"width": 64,
"height": 64,
"size": 2898,
"relative_path": ".thumbs/Can Plug - 0s 18m-64x64.png"
},
{
"width": 400,
"height": 300,
"size": 22379,
"relative_path": ".thumbs/Can Plug - 0s 18m-400x300.png"
}
],
"print_start_time": 1690123794.0230966,
"job_id": "00050F",
"filename": "Can Plug - 0s 18m.gcode"
}
}
```

**Comment by marcolivierarsenault** [comment]
Heads up. 
I did not forget about this, just not sure what the issue is, and I struggle to replicate

**Comment by spikeygg** [comment]
Cool, thanks for the heads up. If you think of anything that I can do
to help with your debug please let me know. I'm ready to try anything. :P

**Comment by spikeygg** [comment]
By the way, this seems to be hit and miss on my setup (mostly miss). I printed three things over the last couple of days using the same slicer and setup. The first thing didn't work for `Time Left`, `ETA`, and `Duration`. The second thing actually worked and now I'm printing the third thing and it's broken again. They're all three different items but generated at roughly the same time with the same slicer and setup. 😒

**Comment by marcolivierarsenault** [comment]
This is weird... I really wonder what is not working. Have you spot a diffence in the logs when it works or when it does not

**Comment by spikeygg** [comment]
> Have you spot a diffence in the logs when it works or when it does not

no, the only thing from the HA logs for moonraker is this benign message:
`2023-11-01 21:35:20.215 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration moonraker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

I'm not really sure how to even debug this condition but it's pretty easy to replicate.

**Comment by marcolivierarsenault** [comment]
Can you get a copy of the log when it work and one when it does not:

[HomeAssistant debug logs](https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log)

**Comment by spikeygg** [comment]
I can't seem to get it to work again. I've printed three things since the working one and every one of them has the issue. 🤬

**Comment by marcolivierarsenault** [comment]
@spikeygg can you take a look at getting the logs plz
[HomeAssistant debug logs](https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log)

**Comment by spikeygg** [comment]
> @spikeygg can you take a look at getting the logs plz

I'm printing some things tonight and tomorrow to try to get it to pass and fail with debug logging enabled but I don't have high hopes. The prints I'm doing are like 2 hours each and it seems like shorter prints always only show the failing condition.

Separately, do you know how the "Print Time Left" is calculated? Because whatever the subtraction is -- it goes negative. It's like the "base" value is zero or too small. That's gotta be some kind of hint... I noticed on the prints where it seemed to work, partially through the print it crossed through zero and those three entities were broken from then on. Here's a bunch of prints I did from the 10th of November to the 13th showing the weird signature:
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1015891/dd851cf6-eadc-4825-bc0d-e6eac93a10a0)

That big spike was the start of a very long print which became paused due to a printing hiccup while I wasn't home for a few hours so the printer sat idle until I came home to restart it. You can see it paused a few times thereafter but had passed through zero so the "Print Time Left" was negative. It's almost like shorter prints just use a "base" value of zero and larger prints have a non-zero number but the time-elapsed eventually becomes much larger than that "base" value creating a negative result.

Any ideas?

**Comment by spikeygg** [comment]
Here's a new one, but it wasn't ever showing a positive "Print Time Left" value. :-/
[home-assistant_moonraker_2023-11-27T01-00-02.069Z_moonraker.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13468685/home-assistant_moonraker_2023-11-27T01-00-02.069Z_moonraker.log)

**Comment by marcolivierarsenault** [comment]
yeah, likely the issue. Will think about a workaround.

**Comment by marcolivierarsenault** [comment]
I pushed an update, can you verify that it works 

(after updating to 0.10.1)

**Comment by marcolivierarsenault** [comment]
reopen if needed

**Comment by JossPer0** [comment]
I have a similar issue, except that my print time is a negative second's amount.  Print ETA = Unknown, Print Projected Total Duration = 0s. Did you find anyway to sort this.
