### ISSUE TITLE
Print progress wrong

### ISSUE THREAD

**Issue by MattiaConfalonieri** [marcolivierarsenault/moonraker-home-assistant#160]
Print progress is wrong when start, immediately after start Print progress is 9% until first refresh.

**Comment by pkejval** [comment]
Can't agree with you. It's working on my end. Newest version of HomeAssistant, this integration and Moonraker/Klipper.

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/48015347/7e10d2e0-c8ce-41c6-b4a9-bf54dc3d252d)

**Comment by marcolivierarsenault** [comment]
Can you enable full debuging logs: https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

Then wait 2-3 min, start a print (Validate the error in Home Assistant (screen shot if you can) )

Then wait another 2-3 min (another Screenshot when it works) 

You can stop logging and send the logs and screenshots

**Comment by MattiaConfalonieri** [comment]
Here log and screenshot requested
<img width="888" alt="Screenshot 2023-07-16 at 10 04 29" src="https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/8712089/f16d9c5a-de23-46f1-b4d4-0fab70c561b5">
<img width="386" alt="Screenshot 2023-07-16 at 10 07 43" src="https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/8712089/fcb1f678-6ffc-46ab-9f92-dbd9eaf09304">
<img width="1697" alt="Screenshot 2023-07-16 at 10 09 58" src="https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/8712089/2806bea2-f58d-4875-9e98-370dfdebb57b">

**Comment by marcolivierarsenault** [comment]
Do you have longer logs (I want to see how the value move for 2-3 minute on each side of the printing (before you start it, right after you started it)
