### ISSUE TITLE
unit_of_measurement is "°" when it should be "°C"

### ISSUE THREAD

**Issue by grmocg** [marcolivierarsenault/moonraker-home-assistant#163]
## Version of the moonraker integration
0.9.1

## Describe your setup

One klipper/Moonraker/Mainsail printer, and one Klipper/Moonraker/Mainsail

## Describe the bug

The extruder, etc. temperatures have a unit_of_measurement of "°", which should be "°C".

## Moonraker Logs

N/A

**Comment by marcolivierarsenault** [comment]
Good catch, will fix

**Comment by marcolivierarsenault** [comment]
shipped
