### ISSUE TITLE
Make refresh interval configurable

### ISSUE THREAD

**Issue by nelsongraca** [marcolivierarsenault/moonraker-home-assistant#165]
## Is your feature request related to a problem? Please describe.

30 seconds between refreshes is too high for my use case as sometimes my first layer takes less than that, rendering my automations based on that fail

## Describe the solution you'd like

I have adjusted manually in the code for 5 seconds but I would like to either have it lower hardcoded or configurable.

**Comment by marcolivierarsenault** [comment]
Related to https://github.com/marcolivierarsenault/moonraker-home-assistant/issues/168

(will be tracking the progress over there)
