### ISSUE TITLE
How many items are supposed to show up in total?

### ISSUE THREAD

**Issue by NonaSuomy** [marcolivierarsenault/moonraker-home-assistant#167]
Hello,

I see 101 Items in which raspberry/mcu temp is missing.

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/4fd466a7-3e05-43e5-b544-374459b0f135)

There should be above the example the other required integrations required to run it.

Maybe add a dumb-down sample or add a basic one with no extra requirements and all the sensors included just to get people off the ground running.

**Comment by marcolivierarsenault** [comment]
I am not sure what you want tbh.

**Comment by NonaSuomy** [comment]
In the example here

`    - entity: sensor.moonraker_raspberry_pi
        name: RPi3
    - entity: sensor.moonraker_mcu
        name: Octopus
    - entity: sensor.atc_3d_temperature
        name: Chamber `


These entities are missing for me.


Was my main issue I was hoping you were going to tell me how many entities show up for you ie is it more than 101 like my picture shows?

The other issue was that the example uses multiple custom front end integrations which are not stated above the example maybe include a link to them: 

custom:mushroom-title-card
custom:bar-card
custom:apexcharts-card
custom:button-card

So I was saying maybe also provide a basic example without custom cards. Using standard home assistant components maybe a grid card with all the sensors in it.

**Comment by NonaSuomy** [comment]
You may also want to mention that you have to change the word moonraker to what your printer shows up as. As mine was mainsailos.

**Comment by marcolivierarsenault** [comment]
You can simply add all entity to a UI from the default Home Assistant feature. 
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/2634090/d0e2308a-f002-4169-915f-878a898deb06)

You get there by going in Setting-Device-Moonraker Integration



Also, that specific dashboard is an exemple of more advance dashboard you can build.

**Comment by NonaSuomy** [comment]
Any information about the main issue? Those temperatures simply not existing in the sensor selection.

**Comment by marcolivierarsenault** [comment]
ok couple of things. 

1) the dashboard example may include sensors not available for everyone (this is all dependant on what your printer reports) as an example my printer reports a total of 111 entities 

2) to verify what is missing, can you output the value of 
http://YOUR_URL/printer/objects/list
This should tell us all available sensors (including temp), Then we can see if/what we are missing

**Comment by NonaSuomy** [comment]
What do you mean? 

Why would it not show up? 

I see the RPi temperature in the screenshot there 55C so why is it not showing up?

Also, why does yours not show MCU temp?

**Comment by marcolivierarsenault** [comment]
Because Moonraker does NOT expose it via the API

**Comment by NonaSuomy** [comment]
So why does your example here have it?
https://moonraker-home-assistant.readthedocs.io/en/stable/dashboard.html

**Comment by marcolivierarsenault** [comment]
As explained here: 
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/2634090/b06b98a6-d1b0-42fa-8b97-502e363525d3)

This is an example dashboard by one member of the community. 

For some reason, his setup does export that specific sensor so he has access to it. 
At the end of the day this app will use anything it receives, but your printer/moonraker need to sends it. 

Looks like by default it does not.

**Comment by NonaSuomy** [comment]
Ok so you do this:

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/5283d184-2df7-4bae-b022-73637a92adbf)

In your printer.cfg add
```
[temperature_sensor raspberry_pi]
sensor_type: temperature_host
min_temp: 10
max_temp: 100

[temperature_sensor mcu_temp]
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100
```
{"result": {"objects": ["webhooks", "configfile", "mcu", "gcode_move", "print_stats", "virtual_sdcard", "pause_resume", "display_status", "gcode_macro CANCEL_PRINT", "gcode_macro PAUSE", "gcode_macro RESUME", "gcode_macro _TOOLHEAD_PARK_PAUSE_CANCEL", "gcode_macro QRCode_Scan", "stepper_enable", "tmc2209 stepper_x", "tmc2209 stepper_y", "tmc2209 stepper_z", "tmc2209 extruder", "heaters", "heater_bed", "heater_fan hotend_fan", "fan", "filament_motion_sensor btt_smart_filament_sensor", "idle_timeout", "bed_screws", "temperature_sensor Chamber_Temp", `"temperature_host raspberry_pi", "temperature_sensor raspberry_pi", "temperature_sensor mcu_temp"`, "gcode_macro PRINT_START", "gcode_macro PRINT_END", "gcode_macro LOAD_FILAMENT", "gcode_macro UNLOAD_FILAMENT", "gcode_macro _RUNOUT_INFO", "gcode_macro SET_ACTIVE_SPOOL", "gcode_macro CLEAR_ACTIVE_SPOOL", "motion_report", "query_endstops", "system_stats", "manual_probe", "toolhead", "extruder"]}}

**Comment by marcolivierarsenault** [comment]
and does it work?

You probably need to reload the integration
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/2634090/e54b9ccf-e343-4ded-b35c-47d1de58b5e8)

Make sure to check the count of entity to see if it goes up

**Comment by NonaSuomy** [comment]
> As explained here: ![image](https://user-images.githubusercontent.com/2634090/256956263-b06b98a6-d1b0-42fa-8b97-502e363525d3.png)
> 
> This is an example dashboard by one member of the community.
> 
> For some reason, his setup does export that specific sensor so he has access to it. At the end of the day this app will use anything it receives, but your printer/moonraker need to sends it.
> 
> Looks like by default it does not.

Yes!
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/168df972-4674-4213-8236-65b931c53535)
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/38994996-f247-4848-bdf4-bf705f827ccc)


As I was saying before instead of just saying hey here is an example that doesn't work... Explain how to get it working fully with all the requirements. Their original dash actually seems to have way more than that which they seemed to have dumbed down a bit for your sample but not all the way.
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/2ff8d5c4-1337-44e6-9890-0ddd500272bc)

**Comment by marcolivierarsenault** [comment]
ok thanks I will update the doc eventually

**Comment by NonaSuomy** [comment]
Thank you!
