### ISSUE TITLE
Using macros

### ISSUE THREAD

**Issue by Technarrus** [marcolivierarsenault/moonraker-home-assistant#17]
Good afternoon! Is it possible to add control via a macro? For example, it would be useful to disable the 3D printer via the HA interface.

**Comment by dwoosnam** [comment]
I'm not sure if this would be along the same idea, but adding buttons to perform REST actions would be cool.

It looks like someone has added the REST services to their config.yaml over [here](https://github.com/mSarheed/home-assistant-moonraker/blob/main/moonraker.yaml). From what I can tell, they then use a button in lovelace to call the service. To add push buttons into HA from the integration to perform these tasks would be great!

I can imagine macros being harder based on the variations of names.

**Comment by marcolivierarsenault** [comment]
@Technarrus We will be looking at Macro, not sure if the first. iteration will be able to accept parameters,

**Comment by marcolivierarsenault** [comment]
added in release 0.5.0
