### ISSUE TITLE
Custom Device Name when adding

### ISSUE THREAD

**Issue by charredchar** [marcolivierarsenault/moonraker-home-assistant#178]
## Is your feature request related to a problem? Please describe.

When adding a printer it uses the hostname of the device. This is an issue if you have multiple printers on one device or your hostname doesn't match what you want the device to be labeled in HA. Using the device's `Rename` option in HA does not rename all of the entities either.

## Describe the solution you'd like

The best option would be to have a field to enter the Device name when you're adding it so it won't default to the hostname. Secondary would be to have the `Rename` feature in HA function properly to rename all entities under a device.

**Comment by marcolivierarsenault** [comment]
Hey this is great feedback, can you clarify which entities does not get renamed properly?

**Comment by charredchar** [comment]
None of them do. I am able to rename the device itself but it does not ask if I want to rename all associated entities along with it like other devices do. I can also rename each entity by hand but in my case that is 400 entities for just one printer.

**Comment by marcolivierarsenault** [comment]
Ok, there seems to be a glitch in the naming, will look for it eventually.

Thanks for reporting

**Comment by busheezy** [comment]
Thanks for your amazing work. I have temporarily made a repo for myself to use.

https://github.com/marcolivierarsenault/moonraker-home-assistant/compare/main...busheezy:moonraker-home-assistant:feature/printer-names

Being able to specify the name will really help us with multiple printers on the same hostname.

**Comment by marcolivierarsenault** [comment]
This looks great, please open a PR, I would be happy to merge your contribution.

*Might need to add some tests and info to the documentation, but it looks great

**Comment by busheezy** [comment]
I will write some tests soon, look into the docs, and then make a PR.

**Comment by marcolivierarsenault** [comment]
shipped
