### ISSUE TITLE
[speeder pad of FLSUN] Camera into Home Assistant

### ISSUE THREAD

**Issue by titou4307** [marcolivierarsenault/moonraker-home-assistant#19]
Hello

I have install the integration on my Home Assistant and it was connected nice with the speeder pad of my printer 3D FLSUN V400

For complete the information : FL SUN V400 has a tablet speeder pad where is installed into this pad Mainsail, moonraker and klipper....

My webcam is connected to the speeder pad and I have access to the video into the URL Mainsail....
How does I must do for to have the video into Home Assistant ? If it possible

**Comment by marcolivierarsenault** [comment]
Hey, 

Can you get me a copy of your logs please. 

Try to enable logging .
![image](https://user-images.githubusercontent.com/2634090/222599015-e13ba59b-09af-42f3-b9f3-1609c92a8d85.png)

Then go try to look at the device or the entities, try to reload the integration. 

Then can you send the logs here

**Comment by marcolivierarsenault** [comment]
Can you also show me what this gives your: 
`http://192.168.1.2/server/webcams/list`

Replace IP with your Printer IP

**Comment by marcolivierarsenault** [comment]
@titou4307 ☝️

**Comment by titou4307** [comment]
Hello
With the `http://192.168.1.2/server/webcams/list`
I have a JSON to download I have put in txt here....

[list.txt](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/10885898/list.txt)

**Comment by marcolivierarsenault** [comment]
Can you check in your mainsail webUI, what is the camera/crownest details
https://user-images.githubusercontent.com/12702322/198850218-a8e12baf-f057-40c5-8203-9cf5ff7d1efa.jpg

**Comment by marcolivierarsenault** [comment]
For the Logs, you can go in 
- Home-Assistant
- Settings
- Device

Then you can click the 3 littles dots and enable logs

**Comment by titou4307** [comment]
Does it you need ? : 
![Mainsail](https://user-images.githubusercontent.com/56826797/222836175-b52b0b2c-730c-42dd-b3d2-1b1187913568.png)

I have enable the log ....
But How this log are ? for made copy and paste here ??

**Comment by marcolivierarsenault** [comment]
If you have the log enable, then on the same sub menu you can click to reload the app

Then click the same sub menu and click disable log. 

It should download a log file

**Comment by titou4307** [comment]
[home-assistant_moonraker_2023-03-03T23-13-13.575Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/10886862/home-assistant_moonraker_2023-03-03T23-13-13.575Z.log)

**Comment by marcolivierarsenault** [comment]
Look like there is something fishy with your moonraker. 
1) have you try restarting the pi? (or whatever device use it)

If you still have the same 404 error with the `http://192.168.1.2/server/webcams/list` (make sure to replace IP)

Can you login ssh on your device and get this log: `/tmp/moonraker.log.`

**Comment by titou4307** [comment]
Hello
I have found this files...
[moonraker-3.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/10887149/moonraker-3.log)
[moonraker-1.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/10887150/moonraker-1.log)
[moonraker-2.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/10887151/moonraker-2.log)

**Comment by marcolivierarsenault** [comment]
I am pretty sure there is some setup thing to fix on your moonraker, 

The right query hits your moonraker `2023-03-03 21:33:04,895 [app.py:log_request()] - 404 GET /server/webcams/list (192.168.1.16) [No User] 9.36ms` 

But you have a user/permission error. 

Looks like other have got this issue

https://www.reddit.com/r/klippers/comments/ugdle8/unable_to_connect_over_lan_to_moonraker/
https://github.com/Arksine/moonraker/issues/321
https://github.com/Arksine/moonraker/issues/568

**Comment by marcolivierarsenault** [comment]
At this point I am 98% convinced the issue is not with the integration

**Comment by titou4307** [comment]
Hello @marcolivierarsenault 

My Klipper Mainsail Moonraker is into the speeder pad of FLSUN (not a PI) so I don't know where is this log
Look at this video : 

https://www.youtube.com/watch?v=dQcC7aBL7oM

I will try to SSH and navigate into speeder pad... And read the 3 links...

**Comment by marcolivierarsenault** [comment]
I don't have this equipement I can't help you debug so much. Sorry.

**Comment by marcolivierarsenault** [comment]
Hey, Right now this integration does not support device using FLSUN. 
Until we can get our hands on one and develop or someone propose a fixing patch, not much we can do.

**Comment by joaomcampos** [comment]
I find myself in the same situation, also have a Flsun v400, same behaviour.

**Comment by MTrab** [comment]
+1 on no cam.

`/server/webcams/list` lists the cam as available, but Home Assistant never picks it up and no entity created for the cam

**Comment by marcolivierarsenault** [comment]
@joaomcampos I think you are onto something.

can you tell me what this gives you
http://192.168.1.2/server/webcams/list

(replace the IP with your moonraker IP)

**Comment by joaomcampos** [comment]
{"error": {"code": 404, "message": "Not Found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/pi/moonraker-env/lib/python3.8/site-packages/tornado/web.py\", line 1681, in _execute\n    result = self.prepare()\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 909, in prepare\n    raise tornado.web.HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not Found\n"}}

**Comment by marcolivierarsenault** [comment]
ok I think I get the issue. 

----
(Note for future me) 

With `FLSUN` the `http://192.168.1.2/server/webcams/list` return a 404, we can't grab the camera path from the API, we can probably try to hardcode it.

**Comment by marcolivierarsenault** [comment]
@joaomcampos any chance you can get me a dump of your HA logs
https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html

**Comment by marcolivierarsenault** [comment]
@titou4307 @joaomcampos 

Can one of you test this branch. `try_hardcode_cameras`

Easiest is to go in your HA install, 
Replace the file `custom_components/moonraker/camera.py` with this file. https://raw.githubusercontent.com/marcolivierarsenault/moonraker-home-assistant/try_hardcode_cameras/custom_components/moonraker/camera.py

Let me know if it works

**Comment by titou4307** [comment]
@marcolivierarsenault 

Hello
I have try this middle of day
After delete old file camera.py, I have put the file you give by link here....

I have the camera view in the add on....

**Comment by marcolivierarsenault** [comment]
Thanks @titou4307 for the help, 

We finally have a fix, fresh of the merge. 

So to get the latest code (while waiting for the new release) please download the **main** verison of the code. 

DEtails here: https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html

**Comment by titou4307** [comment]
No Problem
I am here for to help .... too....
