### ISSUE TITLE
The camera on creality K1 is not shown

### ISSUE THREAD

**Issue by sendorm** [marcolivierarsenault/moonraker-home-assistant#202]
The creality K1 has a root bypass and also has been open sourced very recently. The problem is 
http://192.168.1.1/server/webcams/list returns 404 while (replaced the ip with printer ip)

http://192.168.1.1:7125/server/webcams/list returns the required list. I was able to add the camera from general camera entity but it would be great if this integration managed to integrate it seamlessly. Also the gcode preview camera is not available.

fluidd and moonraker are latest version. Unfortunately the printer is using an old klipper version. 

The 80 port is not available as it is used by the creality's own web server. 

All other entities work as intended.

**Comment by marcolivierarsenault** [comment]
have you tried configuring the port in the integration?

**Comment by sendorm** [comment]
This problem seems to be fixed. I've just readded the integration.

**Comment by pollinolas** [comment]
> This problem seems to be fixed. I've just readded the integration.

Same herea,no camera and thumbnail neither,added port and api Keys and keeps without cams entity
