### ISSUE TITLE
Error when turning on/off the printer lights - argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by rursache** [marcolivierarsenault/moonraker-home-assistant#203]
## Version of the moonraker integration

0.10.0

## Describe your setup

Elegoo Neptune 4 Pro with Fluidd (v1.19.0-6184c73).
HomeAssistant (2023.9.2) in docker with `moonraker-home-assistant` installed via HACS

## Describe the bug

I can see both printer lights (extruder and body) in both HomeAssistant and Fluidd. However if I toggle them in HA, the error comes up and the lights don't change. Changing them in Fluidd works as expected

## Moonraker Logs

```
logger: homeassistant
Source: custom_components/moonraker/sensor.py:540
Integration: Moonraker ([documentation](https://moonraker-home-assistant.readthedocs.io/en/latest/), [issues](https://github.com/marcolivierarsenault/moonraker-home-assistant/issues))
First occurred: 12:01:52 PM (60 occurrences)
Last logged: 12:33:59 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 235, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
    update_callback()
  File "/config/custom_components/moonraker/sensor.py", line 480, in _handle_coordinator_update
    self._attr_native_value = self.entity_description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 275, in <lambda>
    value_fn=lambda sensor: calculate_current_layer(sensor.coordinator.data),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 540, in calculate_current_layer
    and "current_layer" in data["status"]["print_stats"]["info"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by marcolivierarsenault** [comment]
Hi, can you get the full debug logs:

Details here: https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

Also make sure during that time when logs are in debug you do trigger that light from HA

**Comment by rursache** [comment]
unbelievable but after I the print finished, i enabled debug logging so I can send you better logs. i try the switches and now they work. is it possible that the switches doesn't work while printing? can you leave this ticket open to try and grab more logs?

**Comment by marcolivierarsenault** [comment]
Yep no issue we can jeep it open

Marc-Olivier Arsenault


Le sam. 16 sept. 2023 à 08:45, Radu Ursache ***@***.***> a
écrit :
