### ISSUE TITLE
Creality K1 LED Light Not an Entity

### ISSUE THREAD

**Issue by akeslo** [marcolivierarsenault/moonraker-home-assistant#205]
## Version of the moonraker integration

0.10.0

## Describe your setup

Klipper, Moonraker, Fluidd

## Describe the bug

Wondering if the LED Light on Creality K1 should be shown within the integration

## Moonraker Logs

2023-09-18 09:59:09.512 ERROR (MainThread) [homeassistant.components.switch] Error while setting up moonraker platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/moonraker/switch.py", line 24, in async_setup_entry
    await async_setup_output_pin(coordinator, entry, async_add_devices)
  File "/config/custom_components/moonraker/switch.py", line 50, in async_setup_output_pin
    if settings["status"]["configfile"]["settings"][obj]["pwm"]:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'output_pin LED'

**Comment by marcolivierarsenault** [comment]
Hi, can you get the full debug logs:

Details here: https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

Also make sure during that time when logs are in debug you do trigger that light from HA

**Comment by sendorm** [comment]
I've added a custom gcode macro to set the led on and off and using them. A switch would have been better though.

**Comment by marcolivierarsenault** [comment]
Can you look at getting the logs,

I would like to fix the switch platform

**Comment by akeslo** [comment]
@marcolivierarsenault  sorry for the delay, thanks for the help. 

Log attached
[home-assistant_2023-11-02T16-00-02.114Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13242004/home-assistant_2023-11-02T16-00-02.114Z.log)

**Comment by pollinolas** [comment]
the same ones here, those errors are also reflected in the log provided in issue #221

**Comment by cashew22** [comment]
@akeslo Can you provide the config file were you define the output_pin ? It will help thanks

**Comment by akeslo** [comment]
@cashew22 I believe this is what you are looking for lmk...

`
[output_pin fan0]
pin: !nozzle_mcu: PB8
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin fan1]
pin: PC0
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin fan2]
pin: PB1
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin LED]
pin:PB0
pwm: True
cycle_time: 0.010
value: 1
`

**Comment by cashew22** [comment]
@akeslo thanks, i'm working on something that will help me fix your issue, maybe later this week I'll have a branch for you to try.

**Comment by cashew22** [comment]
@akeslo Can you using postman or curl do a GET a request on /printer/objects/query?configfile and post the JSON, I think with this I'll be able to fix it.

Example with curl:
curl http://{IP_ADDRESS_OF_PRINTER}/printer/objects/query?configfile

**Comment by akeslo** [comment]
Thanks for all the help on this @cashew22.  Here is the json output
[output.json](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13452356/output.json)

**Comment by pollinolas** [comment]
> @akeslo Quick fix on your side, just change "LED" for "led" and it should work. I'll push a fix for it soon but you can do the change in the meantime.

Hello, with this solution, if Home Assistant detects it but it can no longer be turned on/off from the printer screen, it throws the following error:
!! {"code":"key69", "msg": "The value 'LED' is not valid for PIN", "values": ["LED", "PIN"]}

**Comment by cashew22** [comment]
Thanks for the feedback, You will have to wait for the proper fix then :)

**Comment by akeslo** [comment]
> @akeslo Quick fix on your side, just change "LED" for "led" and it should work. I'll push a fix for it soon but you can do the change in the meantime.

Update this within the config file on the creality k1 ?

**Comment by akeslo** [comment]
@cashew22 I still don't see a switch for the LED as part of the v1 update. Am I missing something on my end?

Thanks.

**Comment by akeslo** [comment]
@pollinolas Ahh I see it now, thank you! Sweet!
