### ISSUE TITLE
Some sensors value (ex: Bed Temperature) are not "reset" to null once the printer is not available anymore (shutdown)

### ISSUE THREAD

**Issue by altimac** [marcolivierarsenault/moonraker-home-assistant#207]
When I shutdown the printer (the power plug is automated to switch OFF 15 min after a print [except if a print is started in this delay], it's enough to let extruder cool down), I've noticed the Bed Temperature sensor value remains at the very last recorded value. It is not set to null (or whatever "no value" is). The MCU is not reachable anyway.

<img width="427" alt="image" src="https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/778986/e565b788-f100-40f8-875c-9a1123a22fab">

## Version of the moonraker integration

I'm runing moonraker-home-assistant integration v 0.10.0

## Describe your setup

Klipper, Moonraker, Mainsail, on Rpi

## Describe the bug

See top of bug report

## Moonraker Logs

[home-assistant_moonraker_2023-09-19T10-36-41.342Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/12658808/home-assistant_moonraker_2023-09-19T10-36-41.342Z.log)

**Comment by altimac** [comment]
27,12°C is definitely not the temperature of my room. It's the very last "true" temperature of the bed before the MCU is disconnected and no sensor value can be retrieved.
Those values (some values / all values ??) should be reset to "none" / "null" values instead of their last valid value.
Thanks

**Comment by marcolivierarsenault** [comment]
Will get fixed when we move to Push mode 
https://github.com/marcolivierarsenault/moonraker-home-assistant/issues/168
