### ISSUE TITLE
no integration auto restart/recheck when moonraker is not available?

### ISSUE THREAD

**Issue by netweaver1970** [marcolivierarsenault/moonraker-home-assistant#22]
If the 3d printer/moonraker is not online when HA reboots, then the integration goes into error at starting and doesn't recover (aka rechecks) automatically.
But if I'm using the http rest call + manual template sensors derived from the rest call result in the configuration.yaml (my old way), then these come back 'alive' automatically.

I do prefer an integration, as you've built, but the need to manually restart it whenever I need to see the info of the printer (after a restart of HA when the printer was off), is kind of limiting.

Any chance of improving that behaviour?

**Comment by marcolivierarsenault** [comment]
Yes that sounds more than reasonable. 
I have to figure out the way to do this cleanly. 

Will fix, no ETA

**Comment by marcolivierarsenault** [comment]
Note for solution

https://developers.home-assistant.io/docs/integration_setup_failures/#handling-offline-or-unavailable-devices-and-services
