### ISSUE TITLE
K1 MAX  dont show thumbnail camera

### ISSUE THREAD

**Issue by pollinolas** [marcolivierarsenault/moonraker-home-assistant#221]
Can´t load images from camera and thumbnails,moonraker integration configuration section with and without port 7125 and with and without api key same results.....no cameras.
I can add it from the generic mjpeg camera integration with the url:
http://192.168.1.235:4408/webcam/?action=stream  (I am using fluidd)
without port or 7125 port doesnt work the generic camera neither

I attach the full debug log
[home-assistant_2023-11-04T10-27-15.681Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13256379/home-assistant_2023-11-04T10-27-15.681Z.log)

**Comment by pollinolas** [comment]
the same ones here, those errors are also reflected in the log provided in issue #221

**Comment by pollinolas** [comment]
The camera problem has been solved by adding it to moonraker.conf, I still have problems with the thumbnail

**Comment by marcolivierarsenault** [comment]
@cashew22 is working on a fix, 
https://github.com/marcolivierarsenault/moonraker-home-assistant/pull/228 will likely fix it

**Comment by marcolivierarsenault** [comment]
Can you give me a new debug log with the 0.10.1 thank you

**Comment by pollinolas** [comment]
> Can you give me a new debug log with the 0.10.1 thank you

sure,here it is
[home-assistant_2023-11-28T14-43-55.858Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13489419/home-assistant_2023-11-28T14-43-55.858Z.log)

**Comment by marcolivierarsenault** [comment]
@pollinolas just to clarify

1) Is the webcam working? 
2) Are you reloading the app, while collecting the logs.
3) What version of Moonraker are you using?

**Comment by pollinolas** [comment]
> @pollinolassolo para aclarar
> 
> 1. ¿Está funcionando la cámara web?
> 2. ¿Está recargando la aplicación mientras recopila los registros?
> 3. ¿Qué versión de Moonraker estás usando?

1. yes
2. I think I remember that yes (I eat very little fish) :)
3. v0.8.0-204-gfb15b2a3

**Comment by WayneManion** [comment]
I have a 'rooted' Creality K1 and the thumbnail does not work in the Moonraker Home Assistant integration for me either. 

I don't have the Creality camera in my K1 yet so I can't comment on the camera stream.

**Comment by marcolivierarsenault** [comment]
@pollinolas and @WayneManion 
I updated some logging info to get more details, 

Can you 

1. Update to latest **main** version ([info](https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html))
2. Get debug logs ([info](https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log))

**Comment by pollinolas** [comment]
> @pollinolas and @WayneManion I updated some logging info to get more details,
> 
> Can you
> 
> 1. Update to latest **main** version ([info](https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html))
> 2. Get debug logs ([info](https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log))

here we go
[home-assistant_2023-12-09T17-50-34.811Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13625182/home-assistant_2023-12-09T17-50-34.811Z.log)

**Comment by marcolivierarsenault** [comment]
ooo did not work, you needed to 'update' the repo. 
Make sure you update, then re-download main

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/2634090/34890ffc-cf08-42a2-b06b-5e6358083857)

Go `A` then `B` then make sure `C` is `6b427c`


I will update the documentation

**Comment by pollinolas** [comment]
I had to select the main branch after redownload....

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: 20:12:11 (1 occurrences)
Last logged: 20:12:11

Error while setting up moonraker platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/moonraker/sensor.py", line 333, in async_setup_entry
    await async_setup_machine_update_sensors(coordinator, entry, async_add_entities)
  File "/config/custom_components/moonraker/sensor.py", line 532, in async_setup_machine_update_sensors
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in sensors])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 532, in <listcomp>
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in sensors])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 547, in __init__
    self._attr_native_value = description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 502, in <lambda>
    value_fn=lambda sensor: f"{sensor.coordinator.data['machine_update']['version_info']['system']['package_count']} packages can be upgraded",
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'system'


and full log:

[home-assistant_2023-12-09T19-15-29.119Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13625420/home-assistant_2023-12-09T19-15-29.119Z.log)

**Comment by marcolivierarsenault** [comment]
ok  @pollinolas shipped new patches.

Can you re-update/download the `main` .. version should be [8ed67e6](https://github.com/marcolivierarsenault/moonraker-home-assistant/commit/8ed67e6fadab64561b5c22396281de0d5ea0ee74)

The new error should be gone, and I should have new info for the debugging (can you share a new log)

**Comment by marcolivierarsenault** [comment]
** We just pushed some more code (un-related) make sure version is [3fcdc06](https://github.com/marcolivierarsenault/moonraker-home-assistant/commit/3fcdc06320aef099820260b38affd3ff5eb3aad1)

**Comment by pollinolas** [comment]
> ** We just pushed some more code (un-related) make sure version is [3fcdc06](https://github.com/marcolivierarsenault/moonraker-home-assistant/commit/3fcdc06320aef099820260b38affd3ff5eb3aad1)

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 21:42:37 (1 occurrences)
Last logged: 21:42:37

Error while setting up moonraker platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/moonraker/sensor.py", line 333, in async_setup_entry
    await async_setup_machine_update_sensors(coordinator, entry, async_add_entities)
  File "/config/custom_components/moonraker/sensor.py", line 537, in async_setup_machine_update_sensors
    [MoonrakerSensor(coordinator, entry, desc) for desc in sensors]
  File "/config/custom_components/moonraker/sensor.py", line 537, in <listcomp>
    [MoonrakerSensor(coordinator, entry, desc) for desc in sensors]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 553, in __init__
    self._attr_native_value = description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 521, in <lambda>
    sensor.coordinator.data["machine_update"]["version_info"][
KeyError: 'version'


[error_log-1.txt](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13625625/error_log-1.txt)

**Comment by marcolivierarsenault** [comment]
New attempt: version 34409fc

**Comment by pollinolas** [comment]
> New attempt: version [34409fc](https://github.com/marcolivierarsenault/moonraker-home-assistant/commit/34409fcd052b0196419eed26669446b877d356a6)

I get the feeling that all these changes are not related to the miniature problem, but rather to the new update sensor function of the machine.

**Comment by marcolivierarsenault** [comment]
yes, but the error you are getting are due to a new feature we are trying to launch.

and I am debuging both problem at the same time

**Comment by WayneManion** [comment]
I got my Creality K1 camera from Amazon finally. The thumbnail and the Creality camera are now working in the Home Assistant integration.

My IP cameras specified in moonraker.conf and working in Fluidd and Mainsail do not work in the Home Assistant integration though.

**Comment by bmorgan99** [comment]
I am running 1.1.1 and thumbnails don't work on my K1 Max.  Did this ever get fixed?
