### ISSUE TITLE
2ns printer

### ISSUE THREAD

**Issue by Eloura74** [marcolivierarsenault/moonraker-home-assistant#224]
hello, I already have my switchwire installed and with all the elements, but how can I get a second printer?

**Comment by marcolivierarsenault** [comment]
you can add a second entry in home assistant 
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/2634090/96bf829a-d954-48bc-8abc-0f402c0f9397)

**Comment by Eloura74** [comment]
i havn't
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/95535946/3756a21f-96bb-4162-8947-992889644109)
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/95535946/91f97305-4a6b-4e99-9540-f0f2e3fbae5c)

**Comment by marcolivierarsenault** [comment]
you simply have an older version of Home Assistant. in the device screen (first screenshot) click to add a new integration (like the first printer you added) and fill the info for your second printer

**Comment by Eloura74** [comment]
ok thanks it's ok ;)
