### ISSUE TITLE
Unable to add integration, missing moonraker_api

### ISSUE THREAD

**Issue by etu** [marcolivierarsenault/moonraker-home-assistant#227]
## Version of the moonraker integration
- I run 2023.11.2 of Home Assistant from the official docker container in podman.
- I just installed the latest HACS from not having used it before, I got 1.33.0.
- I also just installed the latest moonraker-home-assistant version which is 1.10.0.

## Describe your setup
I have a Raspberry pi with Moonraker and Fluidd that talks to a printer with Klipper. This however seems kinda irrelevant for the issue I'm facing since I haven't been able to get to configure the printer yet.

## Describe the bug
I'm unable to add this integration to my home assistant and I do get the following error in my podman log:

So it seems to me that `moonraker_api` wasn't installed automatically, not sure if it's expected to be installed automatically and my knowledge of python modules and pip is fairly limited so I'm not sure if it would help to run pip install on it somewhere in some folder. And if that's the case, which folder?

## Moonraker Logs
```
Nov 23 19:59:29 server-main-elis home-assistant[663681]: 2023-11-23 19:59:29.997 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration moonraker: No module named 'moonraker_api'
```

**Comment by marcolivierarsenault** [comment]
can you restart Home Asssistant and re-install the integration, then restart again

**Comment by etu** [comment]
Indeed, that worked, now I have a working integration :slightly_smiling_face:
