### ISSUE TITLE
Fan speed control support

### ISSUE THREAD

**Issue by lunDreame** [marcolivierarsenault/moonraker-home-assistant#229]
## Is your feature request related to a problem? Please describe.
I want to use the function related to the fan speed of the pluid dashboard in HomeAssistant. In addition, Creality K1 standard fans support three in pure state on fluidid. However, in reality, only one fan comes up in the Home Assist component.

## Describe your setup
Klipper, Moonraker, Fluidd

## Describe the solution you'd like
X

## Additional context
X

**Comment by pollinolas** [comment]
solved in 10.1 version

**Comment by xtraorange** [comment]
I would like to echo this request as well.  I'd really like to add a fan card on my dashboard to be able to adjust fan speed or shut off fans on the fly.

**Comment by UnleashSpirit** [comment]
Hi, same for me

Events are detected but one fan comes up

![image](https://github.com/user-attachments/assets/6236323b-ca6d-480d-b64a-8780b82927c6)
