### ISSUE TITLE
Grab printername from moonraker and database

### ISSUE THREAD

**Issue by NonaSuomy** [marcolivierarsenault/moonraker-home-assistant#250]
## Is your feature request related to a problem? Please describe.
Can you grab the mainsail printer name so I can define multiple printer names on the HA pages?

## Describe your setup

Voron 0.2 Klipper, KlipperScreen, Mainsail, Moonraker, RPi

## Describe the solution you'd like

When you set a name here in the Mainsail UI it creates a database entry here:

Under the mainsail namespace you'll see this information

```json
{"result": {"namespace": "mainsail", "key": null, "value": {"dashboard": {"nonExpandPanels": {"widescreen": []}}, "gcodeViewer": {"klipperCache": {"kinematics": "corexy", "axis_maximum": [117.5, 118, 120, 0], "axis_minimum": [0, 0, -1.5, 0]}}, "gcodehistory": {"entries": ["ls"]}, "general": {"printername": "TurquoiseVoron3DPrinter"}, "initVersion": "2.5.1",...etc
```
You can grab the key like this

http://3DPrinterIP:7125/server/database/item?namespace=mainsail&key=general
```json
{"result": {"namespace": "mainsail", "key": "general", "value": {"printername": "TurquoiseVoron0Bot3DPrinter"}}}
```
## Additional context

The general key won't show up and gives you a 404 error if this is not set:

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/56b690ab-99fc-475d-afd4-cea424252e46)

```
{"error": {"code": 404, "message": "Key 'general' in namespace 'mainsail' not found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 738, in _process_http_request\n    result = await self._do_request(args, conn)\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 714, in _do_local_request\n    return await self.callback(\n\n  File \"/home/pi/moonraker/moonraker/components/database.py\", line 762, in _handle_item_request\n    val = await self.get_item(namespace, key)\n\n  File \"/usr/lib/python3.9/concurrent/futures/thread.py\", line 52, in run\n    result = self.fn(*self.args, **self.kwargs)\n\n  File \"/home/pi/moonraker/moonraker/components/database.py\", line 196, in func_wrapper\n    return command_func(*args)\n\n  File \"/home/pi/moonraker/moonraker/components/database.py\", line 359, in _get_impl\n    ns = self._get_record(namespace, key_list[0])\n\n  File \"/home/pi/moonraker/moonraker/components/database.py\", line 674, in _get_record\n    raise self.server.error(\n\nmoonraker.utils.ServerError: Key 'general' in namespace 'mainsail' not found\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File \"/home/pi/moonraker-env/lib/python3.9/site-packages/tornado/web.py\", line 1786, in _execute\n    result = await result\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 701, in get\n    await self._process_http_request()\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 740, in _process_http_request\n    raise tornado.web.HTTPError(\n\ntornado.web.HTTPError: HTTP 404: Key 'general' in namespace 'mainsail' not found\n"}}
```

After setting it here it will then dump you the name shown above.

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/88772013-78d9-4c80-94fc-754ca154e241)

Don't know if there are other useful things there you may want to grab also for fun like version, kinematics, axis maximum etc.

Thank you.

**Comment by marcolivierarsenault** [comment]
So, we looked at this and it is custom to mainsail and likely causing issue to other setups. 

Right now we are using the hostname of the pi and you can either name it differently or rename it using default HA controls

**Comment by NonaSuomy** [comment]
Why would it cause any issue?

It is just a data point that you could choose or not choose to show in a text label etc.

You can also run multiple printers off one host so they would all have the same hostname.

**Comment by marcolivierarsenault** [comment]
The integration is a moonraker integration, we are sticking with option available in moonraker. In this case, it's a mainsail specific feature. If we take this instead of hostname, not all printer will react the same

**Comment by NonaSuomy** [comment]
This is a moonraker command you wouldn't take this instead of hostname. It would be in addition. Another sensor like value to use etc.
