### ISSUE TITLE
Housing temperatur

### ISSUE THREAD

**Issue by rt1970** [marcolivierarsenault/moonraker-home-assistant#252]
I have housing heater with temp-sensor and Case-Light and 4 Fan´s (0-3)
Printer: QIDI Max 3

please integrate it with target temp
thank you

**Comment by marcolivierarsenault** [comment]
add debug logs while doing a print and before reloading the integration: https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log


We might look at it if we have time, if not prs are welcomed

**Comment by rt1970** [comment]
I hope that can help:

> http://192.168.178.36:7125/printer/objects/query?heater_bed&heater_generic%20hot&output_pin%20fan2&output_pin%20fan3&heater_fan%20hotend_fan&output_pin%20fan0&output_pin%20caselight&output_pin%20beeper&output_pin%20pwc&pause_resume&filament_switch_sensor%20fila&probe&output_pin%20sound&exclude_object&idle_timeout&print_stats&virtual_sdcard&motion_report&query_endstops&system_stats&toolhead&extruder

result:

> {
    "result": {
        "status": {
            "pause_resume": {
                "is_paused": false
            },
            "output_pin sound": {
                "value": 0
            },
            "probe": {
                "last_z_result": 0,
                "z_offset": 0,
                "last_query": false,
                "y_offset": 4.4,
                "x_offset": 28
            },
            "output_pin beeper": {
                "value": 0
            },
            "query_endstops": {
                "last_query": {}
            },
            "heater_bed": {
                "temperature": 18.61,
                "power": 0,
                "target": 0
            },
            "virtual_sdcard": {
                "progress": 0,
                "file_position": 0,
                "is_active": false,
                "file_path": null,
                "file_size": 0
            },
            "toolhead": {
                "square_corner_velocity": 8,
                "max_accel": 10000,
                "homed_axes": "xyz",
                "estimated_print_time": 641554.4742850476,
                "max_velocity": 600,
                "print_time": 607758.4204324879,
                "max_accel_to_decel": 5000,
                "axis_minimum": [
                    -7,
                    -10.5,
                    -6,
                    0
                ],
                "stalls": 0,
                "axis_maximum": [
                    325,
                    325,
                    325,
                    0
                ],
                "position": [
                    0,
                    -10,
                    165.37250000000057,
                    222492.7482492978
                ],
                "extruder": "extruder"
            },
            "exclude_object": {
                "current_object": null,
                "objects": [],
                "excluded_objects": []
            },
            "output_pin fan3": {
                "value": 0
            },
            "output_pin fan2": {
                "value": 0
            },
            "output_pin fan0": {
                "value": 0
            },
            "motion_report": {
                "live_position": [
                    0,
                    -10,
                    165.37250000000057,
                    222492.7482492978
                ],
                "steppers": [
                    "extruder",
                    "stepper_x",
                    "stepper_y",
                    "stepper_z"
                ],
                "live_velocity": 0,
                "live_extruder_velocity": 3.552713678800501e-15,
                "trapq": [
                    "extruder",
                    "toolhead"
                ]
            },
            "system_stats": {
                "sysload": 0.51,
                "memavail": 648320,
                "cputime": 18367.287877
            },
            "idle_timeout": {
                "state": "Idle",
                "printing_time": 0
            },
            "filament_switch_sensor fila": {
                "filament_detected": true,
                "enabled": false
            },
            "heater_generic hot": {
                "temperature": 17.68,
                "power": 0,
                "target": 0
            },
            "output_pin pwc": {
                "value": 1
            },
            "print_stats": {
                "print_duration": 0,
                "total_duration": 0,
                "filament_used": 0,
                "filename": "",
                "state": "standby",
                "message": ""
            },
            "output_pin caselight": {
                "value": 0
            },
            "heater_fan hotend_fan": {
                "speed": 0,
                "rpm": null
            },
            "extruder": {
                "pressure_advance": 0.02,
                "target": 0,
                "power": 0,
                "can_extrude": false,
                "smooth_time": 0.03,
                "temperature": 19.47
            }
        },
        "eventtime": 641530.844212071
    }
}

**Comment by Arturis** [comment]
I came here to request the same thing, so I'm adding my voice to this enhancement request. With my other printers (Ender 3 Pro, Ender 3 V2 Neo, TronXY X5SA) I am at least able to display the CPU/MCU temp and get a rough idea of how hot the enclosure is, but with the Qidi there isnt an option for either that or the actual enclosure temp sensor.

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/6211355/8a07c564-ac6c-4e33-b7bf-3c2b51c9057d)

**Comment by cashew22** [comment]
@Arturis @rt1970 I you can test the PR #300 it would be great. It should add your heater_generic to the integration
