### ISSUE TITLE
Get thumbnail URL to *.png for iobroker visualization

### ISSUE THREAD

**Issue by Suschibomber** [marcolivierarsenault/moonraker-home-assistant#253]
## Is your feature request related to a problem? Please describe.

I would like to display a thumbnail as a preview in my home automation system. I use the ioBroker for this. Unfortunately, I can't find a way to always display the current thumbnail as an html script/widget via an http command.

## Describe your setup

Voron 2.4
Rpi4
ioBroker

## Describe the solution you'd like

I would prefer a URL or a script that always writes a file on the RPi, e.g. Thumbnail.png, which is overwritten with each print and I can thus access it as a unique URL. Or as a JSON script or something similar.

**Comment by marcolivierarsenault** [comment]
This is outside of scope for this integration. This integration is trying to expose native moonraker interface in Home Assistant.
