### ISSUE TITLE
Try this if you have moonraker api connection problems

### ISSUE THREAD

**Issue by jn3va** [marcolivierarsenault/moonraker-home-assistant#256]
If you are trying to configure the integration and have a problem with it connecting to the moonraker API, and see something similar in your Home Assistant logs....

```
Logger: moonraker_api.websockets.websocketclient
Source: runner.py:186
First occurred: 11:52:47 AM (1 occurrences)
Last logged: 11:52:47 AM
Websocket connection error: Cannot connect to host 192.168.1.111:7125 ssl:default [Connect call failed ('192.168.1.111', 7125)]
```

Edit your moonraker.conf file (on your printer)
If "localhost" is specified, 
```
[server]
host: localhost
port: 7125
enable_debug_logging: False
```

replace localhost with 0.0.0.0 and restart the printer

```
[server]
host: 0.0.0.0
port: 7125
enable_debug_logging: False
```

**Comment by marcolivierarsenault** [comment]
This is a great info, we should add in the documentations.

**Comment by teamsuperpanda** [comment]
Thank you for this! Was wondering what I was doing wrong and got deep in router settings for no reason.

**Comment by kenni** [comment]
Thanks a lot, I did a minor point release update of the firmware in my Elegoo Neptune 4 Plus to v1.2.2.65 - and exactly this setting was changed in the update, even though it wasn't mentioned in the changelog. Saved a lot of debugging time, when you have no experience with Moonraker or its API.

**Comment by gerolori** [comment]
> Thanks a lot, I did a minor point release update of the firmware in my Elegoo Neptune 4 Plus to v1.2.2.65 - and exactly this setting was changed in the update, even though it wasn't mentioned in the changelog. Saved a lot of debugging time, when you have no experience with Moonraker or its API.

Same here with Elegoo Neptune 4 Pro to 1.2.2.53, the default firmware had this setting dialed in but it must have changed with the update. Following the steps worked.

**Comment by marcolivierarsenault** [comment]
added in the doc.
