### ISSUE TITLE
Is there a way to change API Key

### ISSUE THREAD

**Issue by jn3va** [marcolivierarsenault/moonraker-home-assistant#257]
## Version of the moonraker integration

1.1.0 HACS installed

## Describe your setup

Elegoo Neptune 4 Plus
Klipper, Moonraker, Fluidd

## Describe the bug

After updating the firmware on the Elegoo the moonraker API key changes.   I added the API key when I set up the integration initially.  Is there a way to change the API key?   Or do I just need to delete and reinstall?    I'm trying to avoid changes to the sensor names in the future.

**Comment by marcolivierarsenault** [comment]
Sadly for now there are no work around, you need to delete the device in HA and re-add it.

**Comment by jn3va** [comment]
All good.  Thank you sir!   And thanks for creating this integration.
