### ISSUE TITLE
missing sensors

### ISSUE THREAD

**Issue by rt1970** [marcolivierarsenault/moonraker-home-assistant#258]
Hi

I miss many Sensors.
I have 127 Entitys (most switches like GCODE etc.) but only 3 sensors:
- My Sensor (? i think Filament Runout Sensor)
- My_cam0 (ok)
- Thumbnail (ok)

Board MKS SKIPR (Armbian)
Can anyone help?

**Comment by marcolivierarsenault** [comment]
can you provide logs please

**Comment by rt1970** [comment]
where can i find log-file?

**Comment by marcolivierarsenault** [comment]
https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

**Comment by rt1970** [comment]
Sorry. too many privacy.
But here error from log:
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 18:11:47 (1 occurrences)
Last logged: 18:11:47

Error while setting up moonraker platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/moonraker/sensor.py", line 350, in async_setup_entry
    await async_setup_basic_sensor(coordinator, entry, async_add_entities)
  File "/config/custom_components/moonraker/sensor.py", line 359, in async_setup_basic_sensor
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in SENSORS])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 359, in <listcomp>
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in SENSORS])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 575, in __init__
    self._attr_native_value = description.value_fn(self)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 123, in <lambda>
    value_fn=lambda sensor: float(
                            ^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by rt1970** [comment]
I have 2 printer with Klipper in my HA. My QIDI Printer show all sensors...

**Comment by marcolivierarsenault** [comment]
You seems to be missing a sensor (bed temperature/target) that we expect is always present. 
Now I realize that sensor may not be there if you don't have a heated bed. 

1) can you confirm wether or not you have a heated bed. 
2) it would also help if you would share a bit more of the log. (you can send it to me via slack, if you prefer) I need to see the API call response from your printer to validate what data is missing that we are expecting

**Comment by rt1970** [comment]
my printer is a Sapphire Max with heated bed. All works fine.
[home-assistant_2023-12-30T18-02-09.903Z.txt](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13798899/home-assistant_2023-12-30T18-02-09.903Z.txt)

**Comment by rt1970** [comment]
my query from
http://192.168.178.55:7125/printer/objects/query?heater_bed&extruder&print_stats&toolhead&display_status&virtual_sdcard&bme280%20enclosure_fan&temperature_sensor%20Raspberry

`{
    "result": {
        "eventtime": 7465.608195809,
        "status": {
            "heater_bed": {
                "temperature": 19.03,
                "target": 0,
                "power": 0
            },
            "extruder": {
                "temperature": 20.15,
                "target": 0,
                "power": 0,
                "can_extrude": false,
                "pressure_advance": 0,
                "smooth_time": 0.15,
                "motion_queue": null
            },
            "print_stats": {
                "filename": "",
                "total_duration": 0,
                "print_duration": 0,
                "filament_used": 0,
                "state": "standby",
                "message": "",
                "info": {
                    "total_layer": null,
                    "current_layer": null
                }
            },
            "toolhead": {
                "homed_axes": "xyz",
                "axis_minimum": [
                    -4,
                    0,
                    0,
                    0
                ],
                "axis_maximum": [
                    310,
                    307,
                    350,
                    0
                ],
                "print_time": 7091.866435244047,
                "stalls": 0,
                "estimated_print_time": 7449.05480572619,
                "extruder": "extruder",
                "position": [
                    164.675,
                    163.78,
                    50.4,
                    149.58350999999968
                ],
                "max_velocity": 500,
                "max_accel": 500,
                "max_accel_to_decel": 250,
                "square_corner_velocity": 2
            },
            "display_status": {
                "progress": 0,
                "message": null
            },
            "virtual_sdcard": {
                "file_path": null,
                "progress": 0,
                "is_active": false,
                "file_position": 0,
                "file_size": 0
            },
            "bme280 enclosure_fan": {},
            "temperature_sensor Raspberry": {}
        }
    }
}`

**Comment by rt1970** [comment]
[home-assistant_2023-12-30T18-38-26.201Z.txt](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/13798970/home-assistant_2023-12-30T18-38-26.201Z.txt)
Only one Printer (Sapphire with MKS SKIPR board)

**Comment by marcolivierarsenault** [comment]
Hey @rt1970 what is you comfort level with GIT?

I have a branch you could test in your setup to see if it works

option 1, checkout `missing_float_data`
option 2, replace the content of `custom_components/moonraker/sensor.py`
[by this file](https://raw.githubusercontent.com/marcolivierarsenault/moonraker-home-assistant/75eda4c3e45733d15c82b81097057b972f102ba0/custom_components/moonraker/sensor.py)

**Comment by marcolivierarsenault** [comment]
merge in main branch
