### ISSUE TITLE
Integration can't connect to camera

### ISSUE THREAD

**Issue by sanmadjack** [marcolivierarsenault/moonraker-home-assistant#266]
I have two printers set up using camera-streamer for the cameras. Both have been added to home assistant, and one is unable to display the camera from the printer. I found this error in the log?:

Error getting new camera image from ender6 Pi Camera: Cannot connect to host 10.0.0.81webcam:80 ssl:default [Name does not resolve]

10.0.0.81 definitely exists.

I am running version 1.1.0 of the integration.
Both are running raspberry pi 3s.
The camera that is working is a logitech 
The camera that is not working is a Pi camera module 3.
Both cameras stream fine to the mainsail interface.
Crowsnest running camera-streamer is used on both printers.
Both machines are running mainsail updated to these versions:
crowsnest v4.1.3-1-gc0c9c418
klipper v0.12.0-98-g5e433fff
mainsail v2.9.1
moonraker v0.8.0-286-gf44fc4b8

Home assistant log: 

[home-assistant_2024-01-28T03-06-05.808Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14074756/home-assistant_2024-01-28T03-06-05.808Z.log)

**Comment by marcolivierarsenault** [comment]
Make sure to download the latest ("main") version 
https://moonraker-home-assistant.readthedocs.io/en/latest/support/latest.html

and you should be able to configure the camera URL manually 
https://moonraker-home-assistant.readthedocs.io/en/latest/entities/camera.html#camera-config

**Comment by sanmadjack** [comment]
That appears to have done the trick. Thank you!
