### ISSUE TITLE
Cannot rename config entry (within Devices & Services)

### ISSUE THREAD

**Issue by DrFate09** [marcolivierarsenault/moonraker-home-assistant#27]
![image](https://user-images.githubusercontent.com/22684695/222923219-c1db3efe-d4f8-4f1f-abd5-77cb1119b8dc.png)

After a fresh install, every time I try and rename the default config entry of "mainsailos" in the Devices & Services menu, it is reset back to "mainsailos" after I navigate away from the menu. 

Small issue but I would like to be able to rename it.

Running release v0.2.0 via HACS. No logging or debugging info needed.

**Comment by cashew22** [comment]
@DrFate09 Do you expect that to also rename all the entity under it ?

If not, i'll have a fix soon for the renaming

**Comment by DrFate09** [comment]
@cashew22 I do not expect that behavior.

**Comment by marcolivierarsenault** [comment]
Will get fix in next release

**Comment by marcolivierarsenault** [comment]
(0.3.0, lauching in few hours)
