### ISSUE TITLE
Add support for other BME680 measurements

### ISSUE THREAD

**Issue by BenBergman** [marcolivierarsenault/moonraker-home-assistant#277]
## Is your feature request related to a problem? Please describe.

Currently this integration pulls the temperature from BME280-style sensors. My sensor is a BME680 (uses the BME280 class in Moonraker) which also provides air pressure, humidity, and "air quality". It would be great to get these into Home Assistant for logging and automating (eg. track when humidity has gotten too high, notify when air quality is poor).

## Describe your setup

My printer is an Artillery Sidewinder X1 running
Klipper, Moonraker, Mainsail, Klipper Screen
Raspberry Pi

## Describe the solution you'd like

When a BME280 device is found on the Moonraker instance, this integration should check if it provides each of pressure, humidity, and air quality. If so, it should add them to Home Assistant.

## Additional context

<img width="681" alt="image" src="https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/142754/ff018d5e-84ac-47cd-92ce-ac2ff48c1f03">

**Comment by marcolivierarsenault** [comment]
@BenBergman we don't have these sensors so we can't really tests and implement. We will need someone with this sensor willing to implement

**Comment by BenBergman** [comment]
I'll poke around in it and see what I can do.

**Comment by BenBergman** [comment]
I'll try to put some more time in later, but for posterity, making a query to the Moonraker API for `"method": "printer.objects.query", "params": {"objects": {"bme280 enclosure": null}}` got me

```
{
  "jsonrpc": "2.0",
  "result": {
    "eventtime": 542200.418648897,
    "status": {
      "bme280 enclosure": {
        "temperature": 21.79,
        "pressure": 985.6027570024027,
        "humidity": 21.03908186195813,
        "gas": 54177.11558804064
      }
    }
  },
  "id": 5153
}
```

I could create 3 more sensors [here](https://github.com/marcolivierarsenault/moonraker-home-assistant/blob/7732b2b89cba54cfc77b71256b2db03d162793a0/custom_components/moonraker/sensor.py#L369) at all times, but I'm not sure if that would give garbage sensors for people with the simpler bme280s. If so, I'll have to see if there is a way to make the above API call to get a list of the available sensors.
