### ISSUE TITLE
Add 'Print Time Remaining' as sensor

### ISSUE THREAD

**Issue by DrFate09** [marcolivierarsenault/moonraker-home-assistant#28]
In an older configuration for Moonraker in HA, I was able to retrieve the remaining print time for my printer (as a countdown). In this integration, I only see the ETA and print durations, not the remaining print time. 

Here's the YAML from the previous config:

    - name: 3d_printer_time_remaining
      unique_id: "<moonraker-ip-address>e12c8def-5ebe-43a4-9f75-605a0c46fc0f"
      state: '{{ (((states.sensor.printer_3d_sensor.attributes["print_stats"]["print_duration"]/states.sensor.printer_3d_sensor.attributes["display_status"]["progress"]- states.sensor.printer_3d_sensor.attributes["print_stats"]["print_duration"]) if states.sensor.printer_3d_sensor.attributes["display_status"]["progress"]>0 else 0)) | timestamp_custom("%H:%M:%S", 0)}}'
      availability: >
        {% set items = ['sensor.printer_3d_sensor'] %}
        {{ expand(items)|rejectattr('state','in',['unknown','unavailable'])
          |list|count == items|count }}
      icon: mdi:timer-sand
      attributes:
        friendly_name: "Time Remaining"

Could we have this implemented? Thanks!

**Comment by marcolivierarsenault** [comment]
This is planned for future release

**Comment by marcolivierarsenault** [comment]
Will be shipped in release 0.4.0 #41
