### ISSUE TITLE
Async startup

### ISSUE THREAD

**Issue by yordanov-alexandar** [marcolivierarsenault/moonraker-home-assistant#285]
## Is your feature request related to a problem? Please describe.

My printer is off most of the time. When HA is restarted moonraker-home-assistant tries to connect to it for a long time and is blocking the rest of the startup so it takes a lot of time.

## Describe your setup
Manta M8P with CB1, klipper, mainsail, moonraker

## Describe the solution you'd like

I don't know if this can be done from the integration side or it needs to be done by home assistant.
Start moonraker-home-assistant asynchronously so it doesn't block the startup process

**Comment by marcolivierarsenault** [comment]
how long does it blog for, could you send a copy of the logs

**Comment by yordanov-alexandar** [comment]
Sorry for the delay - when looking at the logs I identified one more integration that was delaying the startup and needed some time to remove it.
I did two consecutive restarts - one with klipper server on and one with klipper off - I am attaching the logs here(hopefully I managed to clean them from sensitive info :) )
Startup when klipper server is on is about 43 seconds and when klipper server is off is about 84 seconds
[home-assistant.klipper_on.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14631502/home-assistant.klipper_on.log)
[home-assistant.klipper_off.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14631503/home-assistant.klipper_off.log)

**Comment by marcolivierarsenault** [comment]
Solved in the PR #297
