### ISSUE TITLE
Neptune 4 Pro, can't control LED

### ISSUE THREAD

**Issue by pinkfloydFR** [marcolivierarsenault/moonraker-home-assistant#299]
Problem : 
Can't control both led on a Neptune 4 Pro from Home Assitant and Moonracker Intégration.

Config :

Printer Neptune 4 Pro - Firmware 1.1.2.53 - official
Moonracker 1.1.1
HA full updated, on HA OS

printer.cfg : 

```
#####################################################################
# LED Control
#####################################################################
[output_pin caselight]
pin: PB7
pwm: false
shutdown_value:0
value:0.0

[output_pin caselight1]
pin: PC7
pwm: false
shutdown_value:0
value:0.0

[gcode_macro FLASHLIGHT_ON]
description: Turn on Hotend LEDs
gcode:
  SET_PIN PIN=caselight VALUE=1


[gcode_macro FLASHLIGHT_OFF]
description: Turn off Hotend LEDs
gcode:
  SET_PIN PIN=caselight VALUE=0


[gcode_macro MODLELIGHT_ON]
description: Turn on Logo LEDs
gcode:
  SET_PIN PIN=caselight1 VALUE=1


[gcode_macro MODLELIGHT_OFF]
description: Turn off Logo LEDs
gcode:
  SET_PIN PIN=caselight1 VALUE=0


# [gcode_macro FLASHLIGHT_SWITCH]
# description: Switch Hotend LEDs
# gcode:
#   RUN_SHELL_COMMAND CMD=FLASHLIGHT

# [gcode_shell_command FLASHLIGHT]
# command: sh /home/mks/sled2.sh
# timeout: 5.

# [gcode_macro MODLELIGHT_SWITCH]
# description: Switch Logo LEDs
# gcode:
#   RUN_SHELL_COMMAND CMD=MODLELIGHT

# [gcode_shell_command MODLELIGHT]
# command: sh /home/mks/sled1.sh
# timeout: 5.

[gcode_macro FLASHLIGHT_SWITCH]
description: Switch Hotend LEDs
gcode:
    RUN_SHELL_COMMAND CMD=FLASHLIGHT

[gcode_shell_command FLASHLIGHT]
command: sh /home/mks/sled2.sh
timeout: 5.

[gcode_macro MODLELIGHT_SWITCH]
description: Switch Logo LEDs
gcode:
  RUN_SHELL_COMMAND CMD=MODLELIGHT

[gcode_shell_command MODLELIGHT]
command: sh /home/mks/sled1.sh
timeout: 5.

[gcode_macro ALL_LIGHTS]
description: Turn LEDs on/off
gcode:
  RUN_SHELL_COMMAND CMD=FLASHLIGHT
  RUN_SHELL_COMMAND CMD=MODLELIGHT

```

Tested all entities, nothing work : 

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/476ef9b7-5854-4cdd-ad6f-11b4e2250b01)

Rest of the intégration working fine ( Great thanks for the amazing job BTW ! ) : 
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/59d4d3c2-a742-4f30-a3ca-bfca9ec93389)

Any help will be appreciated ! Thanks !

**Comment by pinkfloydFR** [comment]
More information : Doesn't work neither on moonracker, only from the remote screen, so perhaps not a bug from this extension

**Comment by pinkfloydFR** [comment]
Ok, solved myself, perhaps not the fastest/proper way but it work  : 

added this in my printer.cfg : 

```
[gcode_macro Z_LIGHTS]
description: Turn LEDs on/off
gcode:
  RUN_SHELL_COMMAND CMD=FLASHLIGHT
  RUN_SHELL_COMMAND CMD=MODLELIGHT

[gcode_shell_command FLASHLIGHT]
command: sh /home/mks/sled2.sh
timeout: 5.

[gcode_shell_command MODLELIGHT]
command: sh /home/mks/sled1.sh
timeout: 5.
```

moonracker extension add/detect automaticaly a new button :  button.mkspi_macro_z_lights


created in Ha a new bool entity : 
```
bool_neptune_light:
    name: bool_neptune_light
    initial: off
```

finally in nod red, detect the bool change and press the button 'button.mkspi_macro_z_lights'

So no i have a 'switch' in HA for light that is working : 

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/ea726a89-3099-4b58-9133-e2df47096bd3)

**Comment by Zamboca** [comment]
worked like a charm !
