### ISSUE TITLE
No image for thumbnail (Ender 3 v3 KE)

### ISSUE THREAD

**Issue by SandDeath** [marcolivierarsenault/moonraker-home-assistant#301]
Integration version - 1.1.1
There are similar closed issues, however for my Creality Ender 3 v3 KE it does not work
The printer used is Creality Ender 3 v3 KE with Klipper and Fluidd firmware installed according to the official manual on GitHub (https://github.com/CrealityOfficial/Ender-3_V3_KE_Annex)
The fingerprint thumbnail does not appear in my settings, I am attaching the debug log files and a screenshot of the problem
![HA_camera_entity_2](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/25662096/8687bac3-769d-4e5b-b964-6aa828882ead)
![HA_camera_entity_1](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/25662096/cac0bbec-aae2-484d-a478-8c7c7384762c)
[home-assistant_moonraker_2024-03-25T19-18-05.387Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14748634/home-assistant_moonraker_2024-03-25T19-18-05.387Z.log)
![HA_camera_entity](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/25662096/a83f814a-88ab-4c50-ad2e-cb06cb79aa0d)

**Comment by marcolivierarsenault** [comment]
What is your slicer?

**Comment by SandDeath** [comment]
> What is your slicer?

Latest Ultimaker Cura (5.6.0)
In settings enabled "Upload" > "Format" > "UFP with thumbnail"

**Comment by SandDeath** [comment]
In the Fluidd interface, the thumbnail link looks like this in my case
http://192.168.31.52:4408/server/files/gcodes/.thumbs/CE3V3KE_Core%20Tile_PETG_SP.png

**Comment by BeHappy2021** [comment]
I have the same printer and had the same issue. You have to disable the Creality server to get the thumbnail to show.

Follow the instructions for installing the script [here](https://guilouz.github.io/Creality-K1-Series/helper-script/helper-script-installation/)

Once I removed the Creality server the thumbnail started to display.

**Comment by SandDeath** [comment]
> I have the same printer and had the same issue. You have to disable the Creality server to get the thumbnail to show.
> 
> Follow the instructions for installing the script [here](https://guilouz.github.io/Creality-K1-Series/helper-script/helper-script-installation/)
> 
> Once I removed the Creality server the thumbnail started to display.

I installed the script and reinstalled moonraker + fluidd, what do you mean by Creality Server? Deactivating the Creality Web Interface setting in the Customization section?

**Comment by BeHappy2021** [comment]
> I installed the script and reinstalled moonraker + fluidd, what do you mean by Creality Server? Deactivating the Creality Web Interface setting in the Customization section?

Yes, deactivate the Creality Web Interface. Sorry, I forgot what it was called. Will take a few seconds but the thumbnail will then appear in HA as long as you use a slicer that adds them to the Gcode. I've used the Creality one, Cura and Orca and all those proved thumbnails.

**Comment by SandDeath** [comment]
I confirm that it is necessary to do as described:
1. https://guilouz .github.io/Creality-K1-Series/helper-script/helper-script-installation/
2. After reinstalling moonraker and fluidd, you must deactivate the Creality Web Interface
3. Success

**Comment by chicagoandy** [comment]
Link to Instructions for disabling the web interface after installing the script:
https://guilouz.github.io/Creality-K1-Series/helper-script/remove-and-restore-creality-web-interface/

**Comment by babyhuehnchen** [comment]
Disabling the Creality Web Interface does not seem to resolve the issue on K1 SE for me, still not getting a thumbnail
