### ISSUE TITLE
qidi q1 pro no camera no thumbails

### ISSUE THREAD

**Issue by kallejoken** [marcolivierarsenault/moonraker-home-assistant#309]
Hello everyone,
i own a qidi q1 pro, with the latest moonraker version the thumbnails and the camera picture are not transferred. does anyone have a fix to solve this problem?

fluidd 1.19 version
current HA version.

**Comment by theclue** [comment]
Some problem here. I'm using Qidi x-Smart 3

FYI by default Qidi slicer only outputs their own thumbnail format into the gcode, but adding a PNG one too has no effect.

Trying to debug the issue, I manually called Moonraker API REST query for getting the thumbnails and explored the results: all the thumbnails data is correctly pushed back to the callee

**Comment by marcolivierarsenault** [comment]
Hey, could you share a copy of your logs https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

**Comment by theclue** [comment]
Sure! Here's attached

[home-assistant_moonraker_2024-04-09T09-28-41.282Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14916789/home-assistant_moonraker_2024-04-09T09-28-41.282Z.log)

If I can read the log properly, the issue is quite clear: Connection refused to port 80, but the printer is listening on port 10088

I don't remember if I set the right port during integration since it's not visibile on the device setup anymore, but I guess so since the integration works perfectly (aside the camera and thumbnails, ofc)

hope this helps!

**Comment by kallejoken** [comment]
> Sure! Here's attached
> 
> [home-assistant_moonraker_2024-04-09T09-28-41.282Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14916789/home-assistant_moonraker_2024-04-09T09-28-41.282Z.log)
> 
> If I can read the log properly, the issue is quite clear: Connection refused to port 80, but the printer is listening on port 10088
> 
> I don't remember if I set the right port during integration since it's not visibile on the device setup anymore, but I guess so since the integration works perfectly (aside the camera and thumbnails, ofc)
> 
> hope this helps!

a new firmware has been released that releases port 80

https://github.com/QIDITECH/QIDI_Q1_Pro

**Comment by theclue** [comment]
> a new firmware has been released that releases port 80
> 
> https://github.com/QIDITECH/QIDI_Q1_Pro

This applies only to the new Q1 Pro (for now, at least)

nonetheless I'm not sure I want to switch to port 80 for security reasons. One should not be forced to a specific ports just because it's the only port that works IMHO  :)

**Comment by marcolivierarsenault** [comment]
If you try this, does the camera works?
https://moonraker-home-assistant.readthedocs.io/en/stable/entities/camera.html#manual-configuration

Also have you tried playing with this port config? https://moonraker-home-assistant.readthedocs.io/en/stable/connection.html

**Comment by marcolivierarsenault** [comment]
can you shoot me the JSON from this URL
http://WHATEVER IP/server/config

**Comment by kallejoken** [comment]
> Funktioniert die Kamera, wenn Sie dies versuchen? https://moonraker-home-assistant.readthedocs.io/en/stable/entities/camera.html#manual-configuration
> 
> Haben Sie auch versucht, mit dieser Portkonfiguration zu spielen? https://moonraker-home-assistant.readthedocs.io/en/stable/connection.html

yes works without problems

**Comment by marcolivierarsenault** [comment]
can you shoot me the JSON from this URL
http://whateverip/server/config

**Comment by theclue** [comment]
Hi, sorry for the late reply...i had the qidi offline for a while for maintenance and i had not the chance to test.

Atm I haven't a webcam to plug, so I can only test the thumbnails generation. This option doesn't seem to be available to manually setup in the integration: only two options for camera (stream and snapshot) are available as far as i can see.

Ports setup is correct, moonraker port is 7125 (fluidd is on 10088 instead)

I can paste you the json config ofc, but i can see related to thumbnails or something actually

**Comment by marcolivierarsenault** [comment]
@theclue can you shoot me the JSON from this URL
http://you_moonraker_ip:port/server/config

**Comment by marcolivierarsenault** [comment]
stale
