### ISSUE TITLE
Option to unset state_class so the Long Term Statistics are not collected

### ISSUE THREAD

**Issue by WallK** [marcolivierarsenault/moonraker-home-assistant#313]
## Is your feature request related to a problem? Please describe.

By default (after https://github.com/marcolivierarsenault/moonraker-home-assistant/pull/284), a lot of entities have **state_class** set to measurement or similar which enables HA to save long term statistics for them. This grows DB size pretty quickly

## Describe your setup

Klipper, Moonraker, Mainsail
Generic x86 PC

## Describe the solution you'd like

I'd like to have a global option to disable long term statistics for the printer entities. For example, an option to globally unset **state_class** property for them or set it to empty string in the integration settings

**Comment by marcolivierarsenault** [comment]
Assuming you are using the proper `recorder` module from Home Assistant. 

you can disable it in the config https://www.home-assistant.io/integrations/recorder/#exclude

**Comment by WallK** [comment]
Thank you! I've set excludes to "sensor.<printername>*"
It does not clear existing LTS, so I'll check out how it works

**Comment by WallK** [comment]
Ok, after testing -- this is not what I really want
Excluding sensors make it not keep ANY statistics
And I want specifically not keel Long Term Statistics, normal history is beneficial to have

**Comment by marcolivierarsenault** [comment]
Try looking at manual purge

https://www.home-assistant.io/integrations/recorder/#service-purge


I think you can do some level of purging by entity


If you do this one on schedule you can probably limit it to 7 days or something like that.

**Comment by WallK** [comment]
I think [this](https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization) should let me customize state_class of relevant entries

But I think this should be an option in integration, there's no majority in either usecase imho

**Comment by marcolivierarsenault** [comment]
>But I think this should be an option in integration
I disagree, in the spirit of what Home Assistant want to do, setting these sensor as something else than measurements to prevent db recording seems like an anti-pattern. 

I think changing the state_class is not the solution here. 

Try to control the purge

**Comment by WallK** [comment]
First proposed solution (excluding from recorder) did just that, prevented any recording
Having state_class unset just disables Long Term Statistics, not recording in general

And you do have majority of sensors with state_class unset (even if they are technically measuring stuff) because it didn't make sense to include them, right?

With scheduled purge I'll need to catch the moment history transforms into LTS and purge it (which means I'll need to remember changing it if I ever change the history length) if I want the same basic behavior as other sensors in this integration

I'm not suggesting your defaults are in any way wrong or misinformed, just trying to explain why the previous way of things was ideal for me!

**Comment by marcolivierarsenault** [comment]
So I would actually see it the other way around. I want to make sure the default are set correct, which I am not sure right now. 

Do you have exemple of integration that let people change the state_class of a sensor?

**Comment by WallK** [comment]
No, I actually don't, now thinking about it

I was suggesting not giving users direct control of what state_class is set to, but something akin to:

Do you want to keep Long Term Statistics for some sensors? <checkbox set to true by default>

So it will set the predefined number of sensors to "measurement", as the https://github.com/marcolivierarsenault/moonraker-home-assistant/pull/284 does
Or if unchecked will leave the property empty (as it was before)

I'm not sure about the cons to this, to be honest. User confusion? Not the way "state_class" should be used?
But in my book configurability (especially easy to do) is  _usually_ a good thing (:

**Comment by marcolivierarsenault** [comment]
My concern is, measurement is used for more than long term storage. it is also use for statistics. So I want to follow best practices of the home assistant platform. 

Have you seen other integration changing the state_class based on user config?

**Comment by WallK** [comment]
I was sure I published a comment before, but now it's lost to sands of time

No, I haven't seen anything like this before, but I didn't look too closely either
LTS being a part of a history view now made it much more visible than before, so maybe that's one of the reasons
But also most of the integrations I have do not set state_class at all, like yours did before
And it's usually fine

I, as a user, would like to have an option to easily choose LTS behavior in integration settings
Though I don't know if it makes sense from architecture or "the usual way things are done"

Thanks

**Comment by WallK** [comment]
Ah wait, I was confused, I replied to a previous comment again

Not having the state class keeps statistics working, as far as I can see (for measurements specifically, ofc
The only difference is how history is presented in the popup, but it very depends on how much data points there are

Did you get any comments before implementing state_class change?

**Comment by marcolivierarsenault** [comment]
ok so, 

Unless it's best practice in home assistant to do so, I will NOT change the `state_class` based on user config. AFAIK, it is not the way `state_class` is supposed to be used. I absolutely might be wrong, and if it's the case I will revisit that decision. But for now the decision is to not make this an option.

That being said, I will probably spend time revisiting state_class and apply it better.
