### ISSUE TITLE
No time left with Orca Slicer 2.0.0

### ISSUE THREAD

**Issue by pinkfloydFR** [marcolivierarsenault/moonraker-home-assistant#314]
Hi all !

Printer : Neptune 4 Pro  / N4Pro 1.2A - Firmware 1.1.2.53 / Armbian 22.05.0-trunk Buster
Slicer : Orca 2.0.0 / Windows
Moonracker extension : 1.2.0 ( same problem on 1.1.0 )
HA : 2024.4.1

I used to use CURA as a slicer and everything worked for this moonracker extension, but since I've been using ORCA, the time estimation no longer works.    

sensor.mkspi_print_eta return : unknown

Progress and duration are ok.

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/705bc96f-8cb5-459c-8588-b946340a1be5)

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/5b41cb17-d966-45fd-b24e-e796dacafcbe)

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/0d91d072-19cc-4ea2-8629-b711bf78ab2e)

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/c5844142-9d87-4576-9aa7-e7405281c162)

[home-assistant_moonraker_2024-04-07T14-35-27.824Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14897670/home-assistant_moonraker_2024-04-07T14-35-27.824Z.log)

**Comment by marcolivierarsenault** [comment]
Looks like you GCode Metadata does not include 
`estimated_time` and `filament_total` which are both denominator we use to estimate target time and ETA. 


I am not sure if there is another way to get it

**Comment by pinkfloydFR** [comment]
For information, found this info, but i am not very hot to manually update moonracker :(

https://www.reddit.com/r/ElegooNeptune4/comments/1791tac/orca_slicer_not_generating_time_estimate_tag_in/

It's a Moonraker issue, the version Elegoo uses is older and doesn't parse the newer meta tags. It's possible to update Moonraker though and then the time stamps are parsed correctly again.

Basic guide to update Moonraker:
(word of warning: I only did this on the latest Elegoo Firmware from the Discord so you may have issues updating other firmware or issues that I didn't have that could break your Moonraker service and not be recoverable)

WinSCP into the printer as "root" and delete moonraker and moonraker-env folders (located in /home/mks/)

Then in /etc/systemd/system folder find moonraker.services and delete.

SSH as "mks" using PuTTY and run ./kiauh/kiauh.sh (do not update if prompted)

Install Moonraker by selecting 1 (Install) and then 2 (Moonraker)

Choose 8 to go back and then Q to quit KIAUH installer

cd ~
cd ~/moonraker/
./scripts/data-path-fix.sh

Reboot the printer and you should be updated to the latest Moonraker and the estimated time will now parse correctly.

**Comment by marcolivierarsenault** [comment]
So basically folks need to upgrade and this integration should work automagically???

**Comment by pinkfloydFR** [comment]
Correct sir :)

**Comment by marcolivierarsenault** [comment]
All right. I will go ahead and close the issue
