### ISSUE TITLE
Current and total layer not working

### ISSUE THREAD

**Issue by pinkfloydFR** [marcolivierarsenault/moonraker-home-assistant#321]
Moonraker 1.2.0
Printer : Neptune 4 Pro

Hi !

As i actually playing with magnet in my printing, and added an alert in nodered to telegram me it's time to insert the magnet because printer is paused ( thank for this ! ) i just discovered that current layer and total layer are not updated ( wich can help me to estimate time before the pause ) : 

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/6c5551a9-8481-4bda-98cb-06ce135149b2)

Thanks for the integration btw !

**Comment by marcolivierarsenault** [comment]
Hey can you send me a [copy of your logs ](https://moonraker-home-assistant.readthedocs.io/en/latest/support/logs.html#go-full-debug-log)

thanks

**Comment by pinkfloydFR** [comment]
Sorry, my bad for the log. Here it is.

I started the log just before sending a print. Print is 28 layer total. Stopped the print, wait 10s then stopped the log.

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/49475899/103323b6-3bef-4a93-8eee-65ab9da22f14)

[home-assistant_moonraker_2024-04-14T12-41-17.389Z.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/14970757/home-assistant_moonraker_2024-04-14T12-41-17.389Z.log)

**Comment by marcolivierarsenault** [comment]
Hi, @pinkfloydFR is this still an issue?

**Comment by pinkfloydFR** [comment]
Saddly yes, perhaps the problem is from software version of the printer ? will see if i can find it to inform you !

**Comment by marcolivierarsenault** [comment]
for some reason, your printer does not publish either 

- `print_stats.info` 

   ```json
   {'print_stats': {'info': None, 'print_duration': 28.828773472000023, 'total_duration': 214.133049768}}
   ```
- nor `layer_height`

Did it ever worked?

**Comment by pinkfloydFR** [comment]
yes it was working ! but didn't know when and if it was your integration update or my firmware upgrade that 'killed' it :(

**Comment by marcolivierarsenault** [comment]
how fluid are you with git and SSH?

We could have you roll back our integration version to when we released the feature to see if that is the cause?

**Comment by pinkfloydFR** [comment]
Thank for helping, i can handle that yes !

**Comment by marcolivierarsenault** [comment]
yes doing this swap is exactly what we need

then you have to restart home-assistant


0.7.0 is the initial version of this sensor https://github.com/marcolivierarsenault/moonraker-home-assistant/releases/tag/0.7.0

you can try 1.2.0, 0.7.0 or any version in between

**Comment by pinkfloydFR** [comment]
So, here are the news, none of version are working, so i search in my telegram history, because i was sure to have a gif of the interface running for a friend, and guess what.... i never use layer at the beginning, so i think it's not you integration fault but mine ^^

Searching on the net i have a found a python script to query my moonracker, and during my search i ve seen the pretty interesting information :

![image](https://github.com/user-attachments/assets/b24f6376-4365-4844-83d4-3184f6481900)

I will try to understand how to add this in my orca slicer, stay tuned !

**Comment by pinkfloydFR** [comment]
So, tested this : 

![image](https://github.com/user-attachments/assets/13f0429c-8f27-498d-b3cc-a4804329e2e1)

![image](https://github.com/user-attachments/assets/883fe032-f1db-4024-9015-64086c641951)


but despite all my hopes, it's not working....

Perhaps i need to add this in the printer.cfg file. Will continue to investigate.

**Comment by marcolivierarsenault** [comment]
If you add layer_height the integration might pick it up

**Comment by pinkfloydFR** [comment]
Hum i don't know why my printer doesn't return info from the gcode, i investigate on it...

```{
  "jsonrpc": "2.0",
  "result": {
    "status": {
      "print_stats": {
        "print_duration": 159.72446270100045,
        "total_duration": 301.86750664400006,
        "filament_used": 312.3788799999993,
        "filename": "Keyrambit-Horizontal hole_0.2mm_PLA_16m14s.gcode",
        "state": "printing",
        "message": ""
      }
    },
    "eventtime": 5069.792747583
  },
  "id": 4654
}```

**Comment by pinkfloydFR** [comment]
Hi, here are some news from admin in fluidd discord channel : 

Fluidd v1.19.0 was release more than 2 years ago, way before `SET_PRINT_STATS_INFO` was ever added by Klipper

So the problem come from my printer, not your integration !

Sorry for using your time ! Thanks !
