### ISSUE TITLE
Print stop when the integration is activate

### ISSUE THREAD

**Issue by Idaho947** [marcolivierarsenault/moonraker-home-assistant#336]
Hello,

I've got a big issue with this integration. I have a creality pad and an Ender 3 S1 pro. Everything work fine until last update (1.2.0).
My print stop after 40 min, the creality pad came on the main sreen as if I hadn't launched a printout. 
I've tried lots of things (changing the cables, changing the sd card...) but the only thing that has allowed me to find normal operation is to deactivate the integration. On the screen, when the printer's power is not ON, I also get this error message, which I didn't have before.

![PXL_20240504_101716088 MP](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/45599888/cecf844e-cb1b-4c21-86b9-d8733ccbdd41)

**Comment by marcolivierarsenault** [comment]
Can you please send the logs of the printer and the home assistant integration

**Comment by Idaho947** [comment]
My bad it's a missclick in an automation. I put the Creality pad in an automation instead of a plug...
