### ISSUE TITLE
errors wehn printer is off

### ISSUE THREAD

**Issue by mrlordziemniak** [marcolivierarsenault/moonraker-home-assistant#343]
## Describe the bug

When printer is offline, integration generate massive number of errors, it is possible to fix this somehow?

## Moonraker Logs

Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.moonraker
Źródło: custom_components/moonraker/__init__.py:235
integracja: Moonraker (dokumentacja, Problemy)
Pierwsze zdarzenie: 19 maja 2024 19:42:48 (6960 zdarzenia)
Ostatnio zalogowany: 14:54:34

connection to moonraker down, restarting

**Comment by marcolivierarsenault** [comment]
Can you try to install the latest code 

https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html

**Comment by stuckis6er** [comment]
Hello, I'm also getting a lot of error messages. I installed version 1.2.1.

Best regards
Ralf

`Logger: moonraker_api.websockets.websocketclient
Quelle: runner.py:190
Erstmals aufgetreten: 00:56:43 (399 Vorkommnisse)
Zuletzt protokolliert: 10:06:14

Websocket connection error: Cannot connect to host 192.168.178.66:80 ssl:default [Connect call failed ('192.168.178.66', 80)]`

**Comment by freeblazin** [comment]
First off, love the integration!  Really appreciate the dev time in keeping this up.  I also keep my printer powered off when not in use so there is no connection to moonraker in this state.  I believe this enhancement could be fulfilled with 2 changes:

1. A configuration option to provide an entity/state/attribute to check if printer is in the power on state before attempting the connection to moonraker.  I use a smart plug to control power to rPI, The moonraker integration could query this state value and only attempt the connection/re-connection at the poll interval if the state of the provided entity matches.  In my case it would be smart switch in the On state, but could also be any other connectivity check entity like uptime or ping, or even a sensor that is set by webhook or call from printer controller with some code ran at boot time to notify HA that the printer has been powered on.

3. A configuration option to disable logging of the connection error/warning messages for environments where change 1 is not an option.  This would be an advanced option that could be used to prevent log bloat for users who can not or do not implement change 1.

**Comment by mrlordziemniak** [comment]
I have the same setup and smartplug to power on printer:)

**Comment by Mechotronic** [comment]
An easy work around is to add a filter to you HA configuration.yaml. This will filter all connection errors for moonraker. 
`
logger:
  default: error
  filters:
    moonraker_api.websockets.websocketclient:
      - ".*Websocket connection error: Cannot connect to host*"`

**Comment by marcolivierarsenault** [comment]
Can. you please try 1.3.2

**Comment by b2un0** [comment]
had 1.3.2 installed.

printer is offline, home assistant restarted.

i also powered on the printer, reloaded the integration, powered off the printer and restarted HA. error is the same.

Is this error still wanted?


```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 07:35:46 (1 occurrences)
Last logged: 07:35:46

Error setting up entry crafty for moonraker
Traceback (most recent call last):
  File "/config/custom_components/moonraker/__init__.py", line 115, in async_setup_entry
    raise PlatformNotReady(f"Error connecting to {url}:{port}")
homeassistant.exceptions.PlatformNotReady: Error connecting to 192.168.155.111:7125

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/__init__.py", line 119, in async_setup_entry
    raise PlatformNotReady(f"Error connecting to {url}:{port}")
homeassistant.exceptions.PlatformNotReady: Error connecting to 192.168.155.111:7125
```

<img width="609" alt="image" src="https://github.com/user-attachments/assets/8dae388b-2325-45ce-a3e0-8c2edc3b78d9">


<img width="1020" alt="image" src="https://github.com/user-attachments/assets/0664f537-46e1-4041-a500-4b8591f5bb66">

**Comment by marcolivierarsenault** [comment]
Yes, that's the new error when printer is un-reachable. And you should only be getting it once. 

Also, now HA is AWARE that the printer is unreachable and will only retry when manually reloaded (which is following guidance) 

good so it's working. Are you getting multiple errors

**Comment by b2un0** [comment]
yes, now the device integration comes no more available after powered on the printer (waiting für 10 minutes).

**Comment by marcolivierarsenault** [comment]
you now need to click reload 
![image](https://github.com/user-attachments/assets/c98bd76a-8607-4915-b47f-a7e1fa90885a)

**Comment by b2un0** [comment]
seriously? i now should always reload the integration after i powered on the printer?

than i rollback to 1.3.1 👍

**Comment by marcolivierarsenault** [comment]
ok, let me roll this back then.

**Comment by marcolivierarsenault** [comment]
ok will go back to original code, just chatted with Home Assistant devs and the multiple errors in the logs are working like designed 

![image](https://github.com/user-attachments/assets/8abf1f06-182c-43a4-93c4-d145872456da)

**Comment by marcolivierarsenault** [comment]
ok 1.3.3 is available and reverting that change. 

Sadly we will have to use the repeating error. 

Can you confirm it's back like you wanted then we can close this issue

**Comment by quack3d** [comment]
Would @freeblazin's suggestion be possible? Sounds ideal to me. I also have my 3D printer on a smart plug.

**Comment by marcolivierarsenault** [comment]
Hey, no we will not manage multiple device from 1 integration, that is not a best practices from the HA perspective. 

But, Here are couple of work around.

What I do:
I have my printer on a smart plug, but my rPi is always connected. When the rPI is connected, moonraker is up and can reply to the integration.

other solution live with the error message or mute them using this [solution](https://github.com/marcolivierarsenault/moonraker-home-assistant/issues/343#issuecomment-2310346180)

**Comment by quack3d** [comment]
Unfortunately there is no service (action) that can disable an integration built into HA. 😕

**Comment by marcolivierarsenault** [comment]
I added the information about how to silence the logs in the integration documentation. 

Will be closing the issue

**Comment by b2un0** [comment]
take a look into the Hoymiles DTU Integration for HA
https://github.com/suaveolent/ha-hoymiles-wifi

I have had such a DTU for more than a week now.

The DTU is only online and accessible when the solar panels are generating power.

ThisHoymiles integration recognises this and shows me the DTU as disconnected during this time.
