### ISSUE TITLE
Thumbnail not showing on multi-instance setup

### ISSUE THREAD

**Issue by srbjessen** [marcolivierarsenault/moonraker-home-assistant#355]
## Version of the moonraker integration
1.2.1

## Describe your setup

Macbook Pro 2014
Linux Mint
![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/92088582/2f2d9ff9-180f-4b0b-a72d-64ee3bf48248)
Mainsail
2 printers connected (Biqu BX and JGMaker Artist-D Pro)
separate folders and instances

## Describe the bug

Thumbnail doesn't show, just says "inactive" constantly.
Orcaslicer, prusaslicer, superslicer gives same problem.
300x300, 32x32 PNG thumbnails in slicers.

## Moonraker Logs
[home-assistant_moonraker_2024-06-08T00-01-55.555Z.log](https://github.com/user-attachments/files/15745874/home-assistant_moonraker_2024-06-08T00-01-55.555Z.log)
Not sure where to find config. Nothing in my yaml's

**Comment by marcolivierarsenault** [comment]
what is your printer model. 


Also you specify multi-instance. Does it work in single instance

**Comment by Subcode** [comment]
Im having the same issue, looks like its not looking on the right port.
Single instance,

2024-06-09 04:58:22.663 DEBUG (MainThread) [custom_components.moonraker.camera] Trying to get thumbnail 
2024-06-09 04:58:22.663 DEBUG (MainThread) [custom_components.moonraker.camera] Thumbnail new_path: .thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png
2024-06-09 04:58:22.664 DEBUG (MainThread) [custom_components.moonraker.camera] Fetching new thumbnail: http://192.168.1.182/server/files/gcodes/.thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png
2024-06-09 04:58:22.699 DEBUG (MainThread) [custom_components.moonraker.camera] Trying to get thumbnail 

It is trying to look at:
http://192.168.1.182/server/files/gcodes/.thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png
But the correct url would be:
http://192.168.1.182:7125/server/files/gcodes/.thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png

**Comment by srbjessen** [comment]
> what is your printer model.
> 
> Also you specify multi-instance. Does it work in single instance

1x Biqu BX 
1x JGMaker Artist-D Pro

Both show thumbnails from slicer in Mainsail interface, but nothing is passed on to HA.

Only have this setup with multi-instance, only specified in case it matters :-)

**Comment by srbjessen** [comment]
> Im having the same issue, looks like its not looking on the right port. Single instance,
> 
> 2024-06-09 04:58:22.663 DEBUG (MainThread) [custom_components.moonraker.camera] Trying to get thumbnail 2024-06-09 04:58:22.663 DEBUG (MainThread) [custom_components.moonraker.camera] Thumbnail new_path: .thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png 2024-06-09 04:58:22.664 DEBUG (MainThread) [custom_components.moonraker.camera] Fetching new thumbnail: http://192.168.1.182/server/files/gcodes/.thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png 2024-06-09 04:58:22.699 DEBUG (MainThread) [custom_components.moonraker.camera] Trying to get thumbnail
> 
> It is trying to look at: http://192.168.1.182/server/files/gcodes/.thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png But the correct url would be: http://192.168.1.182:7125/server/files/gcodes/.thumbs/CE3E3V2_ESP32_Devkit_v4_Snap_Fit_Case_Top-720x720.png

That seems like a reasonable conclusion. Would also have been my guess that it had to do with the ports. Unfortunately I'm not skilled enough to change and test alternative setups/codes.

**Comment by marcolivierarsenault** [comment]
can you ssh in the printer and check what is the exact path of that thumbnail from `/`

**Comment by Subcode** [comment]
For the record, i changed camera.py line 167:
        response = await self._session.get(
            f"http://{self.url}/server/files/gcodes/{new_path}"
        )

to:

        response = await self._session.get(
            f"http://{self.url}:7125/server/files/gcodes/{new_path}"
        )

And now it just works fine.

**Comment by srbjessen** [comment]
Thats awesome, then we just need it to function with multi-instance. In my case port 7126 & 7127Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Subcode ***@***.***> Dato: 09.06.2024  18.59  (GMT+01:00) Til: marcolivierarsenault/moonraker-home-assistant ***@***.***> Cc: srbjessen ***@***.***>, Author ***@***.***> Emne: Re: [marcolivierarsenault/moonraker-home-assistant] Thumbnail not showing on multi-instance setup (Issue #355) 
For the record, i changed camera.py line 167:
    response = await self._session.get(
        f"http://{self.url}/server/files/gcodes/{new_path}"
    )

to:
    response = await self._session.get(
        f"http://{self.url}:7125/server/files/gcodes/{new_path}"
    )

And now it just works fine.

**Comment by srbjessen** [comment]
for one instance the path is: /home/klip/BIQUBX_data/gcodes/.thumbs
for the other: /home/klip/ARTISTD_data/gcodes/.thumbs

I'm guessing that makes it harder, since all names will depend on user setup of multiinstance...

**Comment by marcolivierarsenault** [comment]
Can you try newest version 1.3.0 it allows to configure custom port for the camera and thumbnail (in the [configure option](https://moonraker-home-assistant.readthedocs.io/en/stable/entities/camera.html#manual-configuration))

**Comment by marcolivierarsenault** [comment]
☝️  try this and reopen if needed

**Comment by srbjessen** [comment]
The Thumbnail port fix worked 👍
