### ISSUE TITLE
lost information

### ISSUE THREAD

**Issue by Malvu** [marcolivierarsenault/moonraker-home-assistant#356]
Since the last Moonraker update, the Bed power, bed target, bed temperature information has become unavailable.
is there any way to correct this?
Thanks in advance

**Comment by Master92** [comment]
Happened to me, too and the appeared as new sensors. So what I did is delete the "old" sensors from the printer device and rename the "new" entities to match the previous names. That way I didn't have to change any cards or automations.

**Comment by Malvu** [comment]
> Happened to me, too and the appeared as new sensors. So what I did is delete the "old" sensors from the printer device and rename the "new" entities to match the previous names. That way I didn't have to change any cards or automations.

Thanks to you it works

**Comment by marcolivierarsenault** [comment]
> Happened to me, too and the appeared as new sensors. So what I did is delete the "old" sensors from the printer device and rename the "new" entities to match the previous names. That way I didn't have to change any cards or automations.

This is the solution
