### ISSUE TITLE
FLSUN Speeder pad flashed with Original Klipper - go/no go?

### ISSUE THREAD

**Issue by kwsabq** [marcolivierarsenault/moonraker-home-assistant#368]
## Issue/Question on FLsun Speeder pad running original klipper

Have flashed my FLSun Speeder pad with original klipper (as well as my flsun v400) per this github guide... [here](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad#restore-os-image-file). Will this intergration work now that the pad is running original Klipper or is it more a hardware issue?  

## Describe your setup

FLsun v400 running original klipper from this guide... [here](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad#restore-os-image-file)
Speederpad flashed and running original klipper from same guide above. 

## Describe the solution you'd like

Explanation on if the integration will work or not; is it a hardware problem (regardless of software) or a software problem.

**Comment by marcolivierarsenault** [comment]
I have no clue, good if you could test

**Comment by marcolivierarsenault** [comment]
@kwsabq could you please let us know if it works/or not

**Comment by kwsabq** [comment]
It works perfectly so far. All sensors are present and accounted for, accurate and reliable. I will be doing a 20 hour print today so I will check and log any failures that may happen.

I do not have a camera set up yet, my last one broke. I will be getting one soon and report on camera after that.

**Comment by kwsabq** [comment]
@marcolivierarsenault Pulled a bug log at the 50% mark, no problems to speak of at all. All sensors are correct and update regularly. IP address is stable, no connection lost. Everything seems to be running as intended. Works great on both main dashboard, remote (nabu casa), and mobile! 

Camera is ready to be set up and will report back. Will close issue when the camera has been tested fully.

**Comment by kwsabq** [comment]
### **Closing Comment:**

The Flsun Speeder pad and Flsun V400 flashed with original Klipper from [this ](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad#restore-os-image-filehttps://github.com/Guilouz/Klipper-Flsun-Speeder-Pad#restore-os-image-file)github link works perfectly with this integration. All sensors are accurate and work, macros work as expected, and most importantly the camera works flawlessly. I was able to watch my prints on both my main desktop dashboard as well as my mobile phone dashboard. 

### **Recommendation:**

Adding footnote to HACS download providing link to [this ](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad#restore-os-image-file)github download, (It has an amazing Wiki walk through on how to download and flash Klipper to the speederpad and printer) and stating the integration will only work on an original Klipper build. 

Thank you for your work on this @marcolivierarsenault and I hope this is helpful information for you and others in this community.
