### ISSUE TITLE
Be Able To Change Name Of Printer

### ISSUE THREAD

**Issue by comet424** [marcolivierarsenault/moonraker-home-assistant#369]
## Is your feature request related to a problem? Please describe.

the problem is you cant rename the printer   always renames   to userid   '''mkspi'''
it never sorts by Printer name.. as i have 4 of the same printer
so  import  of 4   mkspi  and then auto entries  all goes in same  card...    so its messed..

should be able to  rename  it... if you even try to rename the printer name   it then says intilazing  and then boom  goes back to mkspi  deletes what you typed
as i wanted it labled 
Printer #1 
Printer #2 
Printer #3 
Printer #4 
as   my 4  3d printers  and then have them in there own cards  but right now its just all in one card cuz of there all just a mkspi  
so a future request to be able to Rename... or  not read "user id"   read "Printer Name"   for what intergration should be pulling

## Describe your setup
4 Elegoo 4 Max printers

Please describe your Printer setup, (especially software stack)
Klipper, Moonraker, Fluidd, Mainsail???
Rpi? other?
using Klipper,moonraker,fluid, mainsail.  and home assistant    they all in one package  well not mainsail or home assistant

## Describe the solution you'd like

be able to rename the Printer name
instead of importing  only  "user id" as the printer name id ...  import the printer name  as the printer name id  instead

**Comment by marcolivierarsenault** [comment]
I am not sure I understand, when you use this option, the name does not stick?? 

![image](https://github.com/user-attachments/assets/d79a4a3f-3a74-40da-8fd8-012fdaca7940)

**Comment by comet424** [comment]
not sure if works i added 2 videos to my one drive account  it  windows capture  didnt do it right in 1 video
also  i took screen shot.. i added Printer 3   again   it adds it  again  
and then the integration  renamed Printer 3 to mkspi

so now you see 2 copies  of Printer 3  and 1 copy of printer 1  in the photo



Hostname  cant be renamed as hostname is userid on the printer...
and i dunno how to change hostname on the printer..
so you SSH  mkspi    into printer  which is the hostname  

and you can see in the other video    when the printer is on    you rename and it says initiazling  and resets back to mkspi  

so it should go by printer name  not hostname 

only way i found i could rename  is   when printer is offline thats why you see Printer #3    
sorry if my sentences sound confusing with my dislexia  it confuses  ppl but makes sense in my head

https://1drv.ms/f/s!AkZ74ugB21kngYon5rmhi22e1g4Wcw?e=aVXtfc

![elegoo ha](https://github.com/user-attachments/assets/6222c3f1-8719-46ad-87bf-8a876ad65643)
![elegoo ha 2](https://github.com/user-attachments/assets/d3018b62-72ad-4908-acff-fd2507e38b86)

**Comment by marcolivierarsenault** [comment]
ok I see, 
So apparently this name change is not working (we should fix it) 

But I am curious what happen if you set the name of the printer when you add the printer (in homeassistant) It does not have to match anything from Fluid/Moonraker. You can name this virtually anything and it should name the printer like you want

https://monosnap.com/file/9HIrZ7o6OFgtf7AMcG9L065VhNkz3e

**Comment by comet424** [comment]
ya that seems to work least at moment i will try my other printers right now i have them offline doing re aranging.. but i tested 1  

labeled it Printer #3  and that held... now ill do tests   like where i found when printer is offline and goes red   the intergration  as it cant connect... and when it turns back on  it renames    from Printer #3  to mkspi  ..  ill be testing that .. but i cant at moment i doing a print job for 6 hours...     but ill get back to you   on the part 2 of the test

first part is like how it worked for me i could rename  it when its offline  but when it comes online it renames it.. but let me get back to u on part 2 of test... first part like your video worked

**Comment by marcolivierarsenault** [comment]
@jamincollins for now, readd the printer and configure the name in the setup configuration

**Comment by jamincollins** [comment]
> @jamincollins for now, readd the printer and configure the name in the setup configuration

I'm not sure, but I think this would break all existing dashboard configs that reference the printer (which is a lot). I'll just live with it for now.

**Comment by marcolivierarsenault** [comment]
I know it's not perfect nor great. But for now it's the best path and I doubt we will have a fix soon. 

sry about that

**Comment by comet424** [comment]
@marcolivierarsenault   ah so your not the coder of the moonraker plugin to be able to fix the rename thing..

ya thats what i ended up doing delete it.. and then add it by the name the first time..
