### ISSUE TITLE
State not updating except when printing

### ISSUE THREAD

**Issue by cf-mp** [marcolivierarsenault/moonraker-home-assistant#374]
I am trying to automate the shutting down of my printers via a Shelly device controller via Home Assistant and run via Alexa.  I was able to write an automation to use the host_shutdown button to shutdown Klipper/Moonraker and then wait 30 seconds and power off the Shelly relay.  Next up, I am trying to have the automation check the state of the state of the printer, as I didn't want it to turn the printer off if it was in the middle of a print.  The issue I am having is that Home Assistant can see the printer via the current_print_state if an actual print is running, paused or completed, but it does not seem to be updating status in Home Assistant if the printer is busy, like if I am running a shaper graph, homing the printer, etc.  Maybe thats not a big deal as I was just using that for testing but it seems like the "busy" status should be passed to Home Assistant as well as a status type.  Trying to see if I am doing something wrong or if this is expected behavior.    Thanks

Current Versions

moonraker-home-assistant pluging 1.2.2
moonraker v0.8.0-379-g346a3d7c  
klipper v0.12.0-208-g49c0ad63
Home Assistant: 
   Core 2024.7.2
   Supervisor 2024.06.2
   Operating System 12.4
   Frontend 20240710.0

**Comment by marcolivierarsenault** [comment]
Can you share the full log and perform this manipulation

https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

**Comment by marcolivierarsenault** [comment]
`Current Print State` should give you this info 
![image](https://github.com/user-attachments/assets/4725fb07-47fd-4324-9c82-c47bd8e42910)

**Comment by marcolivierarsenault** [comment]
reopen if needed
