### ISSUE TITLE
Dark mode 'Moonraker' icon

### ISSUE THREAD

**Issue by DrFate09** [marcolivierarsenault/moonraker-home-assistant#38]
Super nitpicky detail, but the Moonraker integration icon on the 'Device info' screen is very hard to read in dark mode in HA. 

![image](https://user-images.githubusercontent.com/22684695/223016750-95ff2fa0-2d40-42c6-a949-61fd4e25c465.png)

Can we either:
1. Add a dark and light iteration of the icon and change them out based on light or dark mode in HA (is this even possible?)
2. Add a solid background behind the word 'Moonraker' to work on either mode.

**Comment by marcolivierarsenault** [comment]
Looks like we can add those. 

I will try to add it in the next few days

Example: https://github.com/home-assistant/brands/pull/3554/files

**Comment by marcolivierarsenault** [comment]
PR opened https://github.com/home-assistant/brands/pull/4197

**Comment by marcolivierarsenault** [comment]
@DrFate09 if should be fix, can you check on your end. It works on mine
![image](https://user-images.githubusercontent.com/2634090/223421918-eff62930-8d15-4a3f-9512-9e19b2c69e99.png)

**Comment by DrFate09** [comment]
@marcolivierarsenault I'm not seeing the updated icon. I restarted HA and all.

**Comment by marcolivierarsenault** [comment]
I think it is a cache issue, 
Those dark logo/icon are store on Home Assistant codebase not this repo and I can see them updated on my prod repo without code change (or version change).

**Comment by DrFate09** [comment]
@marcolivierarsenault I am able to view the updated asset as of this morning.
