### ISSUE TITLE
Activate Presets from Home Assistant

### ISSUE THREAD

**Issue by me1337me** [marcolivierarsenault/moonraker-home-assistant#390]
## Describe your setup
orcaSlicer, fluidd 1.30.3, moonraker v0.9.2-6-gf735c041, K1 Max

## Describe the solution you'd like

Hey guys,
would it be somehow possible to access and activate configured presets in home assistant?
I can configure them in orcaslicer -> settings -> macros -> Thermal Presets
By this, I could activate the via alexa/node-red automation

Or is there any other way to achieve this?

Thanks a lot!

**Comment by marcolivierarsenault** [comment]
In theory all macros are accessible. 

You might need to create a real macro that triggers the temp presets. 


I am not sure the preset lives in moonrsker/klipper. I think they live in fluid, so we might not have access to it in the API.

**Comment by me1337me** [comment]
yeah, they live in fluidd ;( 
but instead of creating a macro that calls the present, wouldnt it be more reliable to create one that sets the tempe?

**Comment by marcolivierarsenault** [comment]
Yeah that would work too

**Comment by me1337me** [comment]
ok great. so i created the macro and have it available in home assistant.
Do you know how I have to call the macro to send the needed paramters? 
for now i have T_BED and T_EXTRUDER. I tried several things, but failed ;(

**Comment by marcolivierarsenault** [comment]
Yeah. Right now, we only support macro with no params. So you have to create 1 macro per temp preset you want and hardcode the temperatures. 

Not ideal but it's the workaround available
