### ISSUE TITLE
Unable to connect to printer

### ISSUE THREAD

**Issue by Boerny41** [marcolivierarsenault/moonraker-home-assistant#393]
## Version of the moonraker integration
1.3.1

## Describe your setup 
Anycubic Mega SE
BTT skr mini e3 v3
Mainsail
Klipper installed using KIAUH in a Debian (bookworm) VM hosted by Proxmox
(Klipper, Moonraker and Mobileraker work fine, UFW is disabled on the VM)

## Describe the bug

Unable to connect to the printer. Times out after 3 minutes with an unknown error
![image](https://github.com/user-attachments/assets/48722216-ba43-4883-b5ca-082f036dc884)

Proof that 192.168.188.214:7125 is the correct IP:
![image](https://github.com/user-attachments/assets/ba119365-a16a-4e06-8e1c-2535646472e4)
![image](https://github.com/user-attachments/assets/a2252b68-a224-4eff-ad8d-1d552134d575)

## Moonraker Logs

Moonraker-HA logs:
```
2024-08-20 19:33:26.829 ERROR (MainThread) [moonraker_api.websockets.websocketclient] Websocket connection error: Cannot connect to host 192.168.188.214:7125 ssl:default [Connect call failed ('192.168.188.214', 7125)]
2024-08-20 19:35:09.230 ERROR (MainThread) [moonraker_api.websockets.websocketclient] Websocket connection error: Cannot connect to host 192.168.188.214:7125 ssl:default [Connect call failed ('192.168.188.214', 7125)]
2024-08-20 19:39:23.181 ERROR (MainThread) [moonraker_api.websockets.websocketclient] Websocket connection error: Cannot connect to host 192.168.188.214:7125 ssl:default [Connect call failed ('192.168.188.214', 7125)]

```

Moonraker logs:
[moonraker (13).log](https://github.com/user-attachments/files/16679871/moonraker.13.log)

note that the connection attempt from HA does not show up because it never reaches moonraker, however I noticed that the logs contain a part with allowed services and wonderd if the HA-Addon needs to be added?
```
***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
  mobileraker
```

**Comment by marcolivierarsenault** [comment]
Historically this is a problem with either:
- Network configs/firewall
- Printer config

to test network try to ping and connect to the port directly from you HomeAssistant os (SSH) 

but I doubt it's in integration, it does not do anything special

**Comment by Boerny41** [comment]
Sorry for the late response, I was a bit busy. Pinging from HA works just fine, for ssh it is missing the key. I'd guess that the integration does not use SSH for communication since it doesn't ask for a password/key, correct?

**Comment by marcolivierarsenault** [comment]
honestly there is not much I can do to help, as far I can se from the integration perspective, it just does not see the target. unless you find a specific error message on one side or the other, it's going to be hard

**Comment by Boerny41** [comment]
Sadly no error, it just never makes the connection. Thank you anyway!
