### ISSUE TITLE
Total Layer always 0 with Prusaslicer

### ISSUE THREAD

**Issue by JollyRgrs** [marcolivierarsenault/moonraker-home-assistant#397]
HA Setup
HA Core: 2024.8.3
HA Supervisor: 2024.08.0
HAOS: 13.1
HACS Moonraker add-on: 1.3.3

Printer Setup
Klipper: v0.12.0-286-g81de9a86
Mainsail: v2.12.0
Moonraker: v0.9.2-6-gf735c041

The senssor for Total Layers is 0 from Prusaslicer. It is not 0 from Cura, it shows a proper number. It would be nice to have documentation as to what is being looked for so I can use custom gcode to fill in. Prusaslicer does have a "total_layer_count"  and I added the following to my start gcode:

```
;LAYER_COUNT:{total_layer_count}
;LAYER:0
```

Properly, the total layer count for my last print was filled in as "98", but the sensor in HA is still showing 0.

All other sensors seem to populate, just the total layer is 0.

What does the gcode need in order for the Total Layer sensor to be populated correctly?

**Comment by marcolivierarsenault** [comment]
Hey usually it's a metadata issue. 

Can you shoot a copy of your log as you print a job. With the error (no layer) 
https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

**Comment by marcolivierarsenault** [comment]
Look similar to #321

**Comment by JollyRgrs** [comment]
Checking the logs, I saw
`'info': {'total_layer': None, 'current_layer': None}` over and over again. So after looking at the logs (which just send "none" for the values) which did look similar to #321, it prompted me to dig deeper into klipper.

https://moonraker.readthedocs.io/en/latest/printer_objects/#print_stats
specifically the part about `info:`

> info: This is a dict containing information about the print provided by the slicer. Currently this is limited to the total_layer and current_layer values. Note that these values are set by the [SET_PRINT_STATS_INFO](https://www.klipper3d.org/G-Codes.html#set_print_stats_info) gcode command. It is necessary to configure the slicer to include this command in the print. SET_PRINT_STATS_INFO TOTAL_LAYER=total_layer_count should be called in the slicer's "start gcode" to initalize the total layer count. SET_PRINT_STATS_INFO CURRENT_LAYER=current_layer should be called in the slicer's "on layer change" gcode. The user must substitute the total_layer_count and current_layer with the appropriate "placeholder syntax" for the slicer.

So with that, I added this in Prusaslicer printer settings. The only difference there might be in any other slicers is how they handle the variables (in Prusaslicer it is putting them in curly braces),  but the `SET_PRINT_STATS_INFO TOTAL_LAYER=` and  `SET_PRINT_STATS_INFO CURRENT_LAYER=` parts would be universal for any slicer that doesn't send that information.

Start G-code
```
SET_PRINT_STATS_INFO TOTAL_LAYER={total_layer_count}
SET_PRINT_STATS_INFO CURRENT_LAYER=0
```

After layer change G-code
```
SET_PRINT_STATS_INFO CURRENT_LAYER={layer_num}
```

Now my logs show correct information.

```
info': {'total_layer': 29, 'current_layer': 2}}
```

Only problem, my "Total Layer" sensor is still showing 0 (also not sure why my "current layer" sensor always seemed to read correctly even given the "none" status in the logs).

**Comment by marcolivierarsenault** [comment]
Hey can you send me a copy of the logs with the 
`info': {'total_layer': 29, 'current_layer': 2}}`

I am surprise you still have 0 with this log

**Comment by marcolivierarsenault** [comment]
> also not sure why my "current layer" sensor always seemed to read correctly even given the "none" status in the logs)
This is because we have multiple way of calculating it, including the value in metadata, but also the current Z height 

----

In the latest log, the one around `2024-08-28 14:19:57` you still have no total layer in Home Assistant? 
What value do you get, 0 or Null?

**Comment by marcolivierarsenault** [comment]
ok very interesting, so, 

As of now, we look for this info in the GCode metadata This is an example. In a field called `layer_count`
https://github.com/marcolivierarsenault/moonraker-home-assistant/issues/283#issue-2145095679
![image](https://github.com/user-attachments/assets/2d46720a-b11b-4147-816c-0eedabff1953)


Now, you don't have this in your GCode, but you do have it in the `print stats`, so I wonder if I can take both and display if available. Let me try to build a patch

**Comment by JollyRgrs** [comment]
> > also not sure why my "current layer" sensor always seemed to read correctly even given the "none" status in the logs)
> 
> This is because we have multiple way of calculating it, including the value in metadata, but also the current Z height
> 
> In the latest log, the one around `2024-08-28 14:19:57` you still have no total layer in Home Assistant? What value do you get, 0 or Null?

I get 0, not null or unknown, but just 0. (except as you can see when I printed something via Cura).
![image](https://github.com/user-attachments/assets/8cea34a2-3c7e-4754-b603-a240465250b3)

Could you document what exactly is being looked for in the gcode? I could add that to my custom gcode inserts, I just don't know what to add. I thought that adding the info using the SET_PRINT_STATS_INFO would be what is needed (and even finding that was a bit of a tour across various documentations). If you could list out what it currently needs to look like, I can format my gcode to match. In the future, I would agree it would be nice to have it pull from either source (though, handling differences, I'm not sure which would be the source of truth).

I'm also wondering if this throws off my current layer/percent complete. Especially during the start of my script where I have it hold a few mm above the back of the plate while the nozzle warms up, it tells me I am at layer 8 and whatever % that is of the total is what it says my percent complete is (I'm guessing it does calculations based on max Z height and whatever the layer height is to determine how many layers there are for the estimation).

**Comment by marcolivierarsenault** [comment]
Right now we look for layer count  (For the total layer) 

![image](https://github.com/user-attachments/assets/5fa2cb47-8b2d-47c1-a138-dee5a7e8ae12)


For current layer we first check if you have the info in your stats 

```
    if (
        "info" in data["status"]["print_stats"]
        and data["status"]["print_stats"]["info"] is not None
        and "current_layer" in data["status"]["print_stats"]["info"]
        and data["status"]["print_stats"]["info"]["current_layer"] is not None
    ):
        return data["status"]["print_stats"]["info"]["current_layer"]
```

 if not we do the calculation based on height

**Comment by marcolivierarsenault** [comment]
from your logs:

```
2024-08-28 14:19:57.725 DEBUG (MainThread) [custom_components.moonraker] Query Result, uuid: d83efe4d-0924-43d1-8780-c5d5f4e15103: {'size': 2464502, 'modified': 1724822149.3122466, 'uuid': '773edbce-c4a7-4821-918d-089148bef9e7', 'slicer': 'PrusaSlicer', 'slicer_version': '2.8.0+win64', 'gcode_start_byte': 35048, 'gcode_end_byte': 2450358, 'object_height': 36.96, 'estimated_time': 5424, 'nozzle_diameter': 0.4, 'layer_height': 0.28, 'first_layer_height': 0.28, 'first_layer_extr_temp': 200.0, 'first_layer_bed_temp': 60.0, 'chamber_temp': 0.0, 'filament_name': 'Hatchbox PLA (Black)', 'filament_type': 'PLA', 'filament_total': 4929.35, 'filament_weight_total': 14.82, 'thumbnails': [{'width': 300, 'height': 300, 'size': 24308, 'relative_path': '.thumbs/Phone Arm Mount_1h30m_0.28mm_195C_PLA_ENDER3-300x300.png'}, {'width': 32, 'height': 32, 'size': 671, 'relative_path': '.thumbs/Phone Arm Mount_1h30m_0.28mm_195C_PLA_ENDER3-32x32.png'}], 'print_start_time': 1724864464.0206156, 'job_id': '000303', 'filename': 'Phone Arm Mount_1h30m_0.28mm_195C_PLA_ENDER3.gcode'}
```

some other printer spit also `layer_count` now I don't know why does not

**Comment by JollyRgrs** [comment]
It looks like in the response printer.info has the information needed. This seems to be consistent with what klipper is supposed to provide. It seems like you are pulling from server.files.metadata, I might suggest pulling from printer.info or at least supporting data residing there. This is what Klipper documentation mentions. I think the files.metadata very strongly relies on the individual slicer

**Comment by marcolivierarsenault** [comment]
yeah, fully agree, I am starting to think that `printer.info` should be first place we look `server.files.metadata` second 
We will look at making a patch in next few days/week

**Comment by marcolivierarsenault** [comment]
are you able to test the new code

**Comment by marcolivierarsenault** [comment]
If possible, can you try #398 

Simply replace the sensor.py file in your Home Assistant setup

home_assistant_root/custom_components/moonraker/sensor.py

and replace it with https://raw.githubusercontent.com/marcolivierarsenault/moonraker-home-assistant/92ea80a6deae03dbeffeaa588f89c94378d17d75/custom_components/moonraker/sensor.py

**Comment by JollyRgrs** [comment]
I tried out the new sensor.py and great success!
![image](https://github.com/user-attachments/assets/47bbbbcc-7681-45c7-9af4-38a2151ee606)
Thanks for the quick turn around on that!

**Comment by marcolivierarsenault** [comment]
perfect, will ship and this will be part of next Release

**Comment by pieri70** [comment]
> I tried out the new sensor.py and great success! ![image](https://github.com/user-attachments/assets/47bbbbcc-7681-45c7-9af4-38a2151ee606) Thanks for the quick turn around on that!

Hi
Can you please share what code you inserted into your start gcode to let this addon read correctly the  Total layer count?
I tried with last update but still don't have this value that is always zero.
Thanks

**Comment by JollyRgrs** [comment]
> > I tried out the new sensor.py and great success! ![image](https://github.com/user-attachments/assets/47bbbbcc-7681-45c7-9af4-38a2151ee606) Thanks for the quick turn around on that!
> 
> Hi Can you please share what code you inserted into your start gcode to let this addon read correctly the Total layer count? I tried with last update but still don't have this value that is always zero. Thanks
This is what I am using as my custom gcode within prusaslicer 2.9.3

I think the two commented layer lines was me trying to troubleshoot the issue myself. I am setting total layer in the first line as well as current_layer. I then realized that it wasn't moving to 1 on its own and set it to 1 myself below. I might have done the CURRENT_LAYER=1 line after the print_start macro because it would be reset to the wrong layer otherwise? I can't remember (sorry) and I failed to comment why I did it. So I just leave it as is.

```
SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count] CURRENT_LAYER=0
print_start BED_TEMP={first_layer_bed_temperature[0]} EXTRUDER_TEMP={first_layer_temperature[0]}
;LAYER_COUNT:{total_layer_count}
;LAYER:1
SET_PRINT_STATS_INFO CURRENT_LAYER=1
```
