### ISSUE TITLE
Print Time ETA updates without a print happening.

### ISSUE THREAD

**Issue by turulix** [marcolivierarsenault/moonraker-home-assistant#405]
## Version of the moonraker integration
1.3.5

## Describe your setup
HA Running on a self hosted server using docker.
Using Mainsail for the 3d printer with Klipper & Moonrake on an Raspberry Pi 3

## Describe the bug

As you can see, the state changed to completed but the ETA keeps updating anyways and spamming the logs.
![image](https://github.com/user-attachments/assets/04fa2ecb-ae35-4ecf-9004-0eb8f5600db7)

## Moonraker Logs

https://haste.turulix.de/jixibupore.log

**Comment by marcolivierarsenault** [comment]
just push a patch, will get fix in the next release. 

If you want to test early, you can download `main` https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html

Let me know/reopen if it does not fix it.

**Comment by smsalisbury** [comment]
What's the ETA for a release on this? I'm not seeing the `main` branch in the dropdown so I can test it out.

**Comment by marcolivierarsenault** [comment]
I should be merge. What are your download options

**Comment by smsalisbury** [comment]
> I should be merge. What are your download options

Versions 0.1.0-1.3.5

**Comment by marcolivierarsenault** [comment]
ooo they removed main 😮‍💨 

ok, I will make another release. Sorry about that
