### ISSUE TITLE
Moonraker issue

### ISSUE THREAD

**Issue by drumstick77** [marcolivierarsenault/moonraker-home-assistant#407]
Hi all,

I've updated HA and HACS to the latest versions and it seems to have now broken Moonraker.
all entities are now not accessible and when I tried to add them back in, can't seems to be able to connect.
![image](https://github.com/user-attachments/assets/eb66a2b4-cced-4aec-8233-55817dca8004)
Any help would be much appreciated. thanks

**Comment by marcolivierarsenault** [comment]
can you send the logs please. 

What version of HA and the integration are you using. 
https://moonraker-home-assistant.readthedocs.io/en/latest/support/logs.html#go-full-debug-log

**Comment by Rvh91** [comment]
i have a similar issue, in the logs i find the following:

Setup failed for custom integration 'moonraker': Requirements for moonraker not found: ['moonraker-api==2.0.6'].

i updated from 2024.8.3 to 2024.9.1.

**Comment by Rvh91** [comment]
in addition im seeing this in the full logs:

Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 08:23:10 (9 occurrences)
Last logged: 08:23:17

Unable to install package beautifulsoup4==4.10.0: ERROR: Exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper return func(self, options, args) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 455, in run installed = install_given_reqs( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/req/__init__.py", line 65, in install_given_reqs uninstalled_pathset = requirement.uninstall(auto_confirm=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/req/req_install.py", line 715, in uninstall dist = get_default_environment().get_distribution(self.req.name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution return next(matches, None) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 184, in <genexpr> matches = ( ^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions for dist in self._iter_distributions(): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions yield from finder.find(location) File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find for dist, info_location in self._find_impl(location): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl raw_name = get_dist_name(dist) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name name = cast(Any, dist).name ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 457, in name return self.metadata['Name'] ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 444, in metadata self.read_text('METADATA') File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 819, in read_text return self._path.joinpath(filename).read_text(encoding='utf-8') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/pathlib.py", line 1028, in read_text return f.read() ^^^^^^^^ File "<frozen codecs>", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 11514: invalid start byte
Unable to install package beautifulsoup4==4.10.0: ERROR: Exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper return func(self, options, args) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 324, in run session = self.get_default_session(options) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 71, in get_default_session self._session = self.enter_context(self._build_session(options)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 100, in _build_session session = PipSession( ^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 344, in __init__ self.headers["User-Agent"] = user_agent() ^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 177, in user_agent setuptools_dist = get_default_environment().get_distribution("setuptools") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution return next(matches, None) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 184, in <genexpr> matches = ( ^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions for dist in self._iter_distributions(): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions yield from finder.find(location) File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find for dist, info_location in self._find_impl(location): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl raw_name = get_dist_name(dist) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name name = cast(Any, dist).name ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 457, in name return self.metadata['Name'] ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 444, in metadata self.read_text('METADATA') File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 819, in read_text return self._path.joinpath(filename).read_text(encoding='utf-8') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/pathlib.py", line 1028, in read_text return f.read() ^^^^^^^^ File "<frozen codecs>", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 11514: invalid start byte
Unable to install package moonraker-api==2.0.6: ERROR: Exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper return func(self, options, args) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 324, in run session = self.get_default_session(options) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 71, in get_default_session self._session = self.enter_context(self._build_session(options)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 100, in _build_session session = PipSession( ^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 344, in __init__ self.headers["User-Agent"] = user_agent() ^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 177, in user_agent setuptools_dist = get_default_environment().get_distribution("setuptools") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution return next(matches, None) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 184, in <genexpr> matches = ( ^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions for dist in self._iter_distributions(): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions yield from finder.find(location) File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find for dist, info_location in self._find_impl(location): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl raw_name = get_dist_name(dist) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name name = cast(Any, dist).name ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 457, in name return self.metadata['Name'] ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 444, in metadata self.read_text('METADATA') File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 819, in read_text return self._path.joinpath(filename).read_text(encoding='utf-8') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/pathlib.py", line 1028, in read_text return f.read() ^^^^^^^^ File "<frozen codecs>", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 11514: invalid start byte
Unable to install package prettytable==3.10.0: ERROR: Exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper return func(self, options, args) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 324, in run session = self.get_default_session(options) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 71, in get_default_session self._session = self.enter_context(self._build_session(options)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 100, in _build_session session = PipSession( ^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 344, in __init__ self.headers["User-Agent"] = user_agent() ^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 177, in user_agent setuptools_dist = get_default_environment().get_distribution("setuptools") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution return next(matches, None) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 184, in <genexpr> matches = ( ^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions for dist in self._iter_distributions(): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions yield from finder.find(location) File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find for dist, info_location in self._find_impl(location): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl raw_name = get_dist_name(dist) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name name = cast(Any, dist).name ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 457, in name return self.metadata['Name'] ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 444, in metadata self.read_text('METADATA') File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 819, in read_text return self._path.joinpath(filename).read_text(encoding='utf-8') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/pathlib.py", line 1028, in read_text return f.read() ^^^^^^^^ File "<frozen codecs>", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 11514: invalid start byte

**Comment by drumstick77** [comment]
[home-assistant_2024-09-12T10-29-48.506Z.log](https://github.com/user-attachments/files/16977624/home-assistant_2024-09-12T10-29-48.506Z.log)

**Comment by marcolivierarsenault** [comment]
@drumstick77 looks like home assistant can't reach your printer. 

Are you sure you have the right ip port  and that you can reach it from HA

Are you sure there is no key and that Moonraker is listening and accepting connection for HA

**Comment by b2un0** [comment]
mostly its port `80` and **not** `7125` ;)

**Comment by Rvh91** [comment]
my issue was resolved. It seems as if I somehow bricked my HA instance. restoring a backup did not help, but spinning up a new VM and applying the backup there did fix the issue.
