### ISSUE TITLE
Lighting (rgb) controls

### ISSUE THREAD

**Issue by Julian187781** [marcolivierarsenault/moonraker-home-assistant#415]
Feature request;

Hi, i‘d really like it if you‘d be able to implement the light switch controls from within Mainsail/Moonraker into the HA. 
On/Off or Rgb controls would be perfect.

Setup:

Voron 0.2
BTT Pi v1.2
BTT Pico Board
Klipper Expander Board with daisychainable LED Control

## Additional context

![image](https://github.com/user-attachments/assets/4b4d1389-205d-4789-b0ab-0f53349f41eb)

**Comment by marcolivierarsenault** [comment]
Hey Thanks, there is already an ask for this #230 

Feel free to add a vote in the other issue, but for now it's not being worked on
