### ISSUE TITLE
Thumbnail entity not automatically renamed

### ISSUE THREAD

**Issue by DrFate09** [marcolivierarsenault/moonraker-home-assistant#42]
After renaming a device (printer), HA asks if you want to rename the associated entities to reflect the new device name. From what I can tell, all of the entities are renamed other than the thumbnail entity.

Can we also automatically rename the thumbnail entity when prompted?

**Comment by DrFate09** [comment]
I wasn't able to replicate the issue I saw yesterday so I'll say it was a weird one-off occurrence. I'll go ahead and close the ticket.

**Comment by DrFate09** [comment]
@marcolivierarsenault I stumbled upon the cause of the issue. When you first add a device, the thumbnail sensor does not show up in the sensors list, if you then refresh the browser, it then shows up. 

The issue is (very very minor one) if you update the name of the device immediately after adding and before refreshing, the thumbnail sensor is exclude because it is invisible in the sensors list. Once you refresh, the original device name shows up and you then have to manually rename the sensor. 

See attached video for the issue:
https://drive.google.com/file/d/1hN4i8cSPz28wUVpuIpR5IbdifODtbKK2/view?usp=sharing

**Comment by cashew22** [comment]
@marcolivierarsenault It's related to the fact that we add some entity (camera and thumbnail) after the initial setup of the other entity. We will have the same problem with the sensors from #47.

**Comment by marcolivierarsenault** [comment]
@cashew22 any idea how to fix that one?

**Comment by cashew22** [comment]
@marcolivierarsenault We need to find a way to return from _setup_async after all the pending jobs related to entities are done
