### ISSUE TITLE
Current layer is wrong in HASS while correct in Fluidd

### ISSUE THREAD

**Issue by rursache** [marcolivierarsenault/moonraker-home-assistant#430]
## Version of the moonraker integration

1.3.7

## Describe your setup

Elegoo Neptune 4 Pro with Klipper `v0.10.0-530` (cannot update) and Fluidd `v1.30.5`

## Describe the bug

The values of the sensor "current layer" is always wrong. Usually by 5-6 layers but not always.
The correct value is visible in Fluidd:
![image](https://github.com/user-attachments/assets/c405a638-2065-40d8-8a6d-3e33c2ac7465)

but the sensor value is really off:
![image](https://github.com/user-attachments/assets/1af6c97d-f038-471a-b83b-1912ad263c87)

my plan is to create an HASS automation to be notified when X layer is reached on specific prints but I can't do that if the most important value is wrong

## Moonraker Logs

There are no errors in the HASS log related to this

**Comment by marcolivierarsenault** [comment]
I would need a copy of the debug log during a print to troubleshoot. 
thanks

https://moonraker-home-assistant.readthedocs.io/en/latest/support/logs.html#get-a-copy-of-your-ha-logs

**Comment by rursache** [comment]
its happening on EVERY print, its always 5-6 layers wrong. why don't the addon just read from the same place as fluidd?

**Comment by marcolivierarsenault** [comment]
1) I don't know where Fluidd reads it
2) Both this integration and FLuidd reads what is available out of the Moonraker API, and make some calculation to interpret the current layer.

**Comment by rursache** [comment]
if it helps, from what i see fluidd current layer matches what i see in cura

**Comment by marcolivierarsenault** [comment]
In your case you don't have `current_layer` this cause the integration to guess the layer by [manually calculating it](https://github.com/marcolivierarsenault/moonraker-home-assistant/blob/e8f37e91534c2e56ab88c999c1f983aab37f709d/custom_components/moonraker/sensor.py#L878). Now there is a chance that Fluidd calculate it differently.

Based on the [Moonraker Documentation](https://moonraker.readthedocs.io/en/latest/printer_objects/), you can add the `current_layer` 


---
`info`: This is a dict containing information about the print provided by the slicer. Currently this is limited to the total_layer and current_layer values. Note that these values are set by the [SET_PRINT_STATS_INFO](https://www.klipper3d.org/G-Codes.html#set_print_stats_info) gcode command. It is necessary to configure the slicer to include this command in the print. SET_PRINT_STATS_INFO TOTAL_LAYER=total_layer_count should be called in the slicer's "start gcode" to initalize the total layer count. SET_PRINT_STATS_INFO CURRENT_LAYER=current_layer should be called in the slicer's "on layer change" gcode. The user must substitute the total_layer_count and current_layer with the appropriate "placeholder syntax" for the slicer.

**Comment by rursache** [comment]
i'm not reslicing all my files for this. not to mention there is no event for "on layer change" in cura

if fluidd calculates it correctly, this addon must be able to as well. that's why i opened this issue

**Comment by marcolivierarsenault** [comment]
Looks, 
Others don't have this problem, it calculate the right value for me and others, 
I won't be spending time on this

**Comment by rursache** [comment]
"works for me, will close" 

![image](https://github.com/user-attachments/assets/f5962035-e463-487f-88fd-a50e7169ad28)
