### ISSUE TITLE
Connection issue / Log spam when printer is powered off

### ISSUE THREAD

**Issue by BlackHawk1912** [marcolivierarsenault/moonraker-home-assistant#454]
## Version of the moonraker integration
1.5.0

## Describe your setup
Home Assistant 2024.11 container istallation.
Creality K1 with Mainsnail 2.9.0

## Describe the bug
When printer is powered on, everthing works as expected.
When my printer is not turned on (PSU switched OFF), the integration fails  to connect and spams errors. Also the message in the integration overview suggests, that it is constantly trying to reconnect.

![image](https://github.com/user-attachments/assets/ff535aef-c819-4020-a9c3-fb4fb1702bf6)
![image](https://github.com/user-attachments/assets/50df0ce9-f076-48d4-b2a8-19dc7afacc42)

## Home Assistant Logs
Error:
```
Logger: moonraker_api.websockets.websocketclient
Quelle: runner.py:189
Erstmals aufgetreten: 10:38:27 (220 Vorkommnisse)
Zuletzt protokolliert: 15:51:05

Websocket connection error: Cannot connect to host 192.168.178.151:7125 ssl:default [Connect call failed ('192.168.178.151', 7125)]
Websocket connection error: Connection timeout to host ws://192.168.178.151:7125/websocket
```
Warning:
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.moonraker
Quelle: custom_components/moonraker/__init__.py:103
Integration: Moonraker (Dokumentation, Probleme)
Erstmals aufgetreten: 10:38:27 (220 Vorkommnisse)
Zuletzt protokolliert: 15:51:05

Cannot configure moonraker instance
```

**Comment by marcolivierarsenault** [comment]
Hi, 

There is a long discussion in #343 about this and trying alternatives solutions. TDLR, we have not found one. The [Workaround proposed in the documentation](https://moonraker-home-assistant.readthedocs.io/en/latest/connection.html#unreachable-printer) is to silence that log if you want.

**Comment by voed** [comment]
Maybe you can add an option to suppress that error without scan interruption?
