### ISSUE TITLE
Optional sensors not appearing in Moonraker integration

### ISSUE THREAD

**Issue by paulver10** [marcolivierarsenault/moonraker-home-assistant#455]
I've installed the moonraker integration into my HASS setup. Everything is working perfectly, straight out of the box, except for the optional temp and fan sensors which are not appearing unfortunately.

I started building a similar dashboard to the example in your excellent documentation and this is when I made the discovery that these sensors would normally be available if configured in the klipper printer.cfg file.

I've attached screenshots of both the fan and temp config areas in printer.cfg. To test, I also disabled a couple of additional sensors and just focused on the raspberry pi host and mcu temperature sensors, replicating your config example. ( I had different display names originally)

Moonraker integration version is 1.5.0 running on a Pi instance of Home assistant.
HASS details:
Core 2024.12.3
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7

I have a Voron 2.4 with Rapsberry Pi 4b, running Klipper, Moonraker and Mainsail.
klipper v0.12.0-396-gb7233d11
moonraker v0.9.3-3-gccfe32f2
mainsail v2.13.1

I've also attached home assistant logs as per the documented instructions.

[home-assistant_moonraker_2024-12-15T02-26-26.748Z.log](https://github.com/user-attachments/files/18138634/home-assistant_moonraker_2024-12-15T02-26-26.748Z.log)
![hass-moonraker-entity-count](https://github.com/user-attachments/assets/697c4015-87bf-4b49-95b1-151b34f63fbe)
![hass-moonraker-entity-list](https://github.com/user-attachments/assets/23328313-e1a7-44a6-934b-178066a7513f)
![temp-sensors-printer_cfg](https://github.com/user-attachments/assets/bc5c9566-b2bd-4e10-8aa2-ca5a0db60fee)
![fan-config-printer_cfg](https://github.com/user-attachments/assets/6eb4a5e3-5b7c-4800-befe-571774163d0c)

**Comment by marcolivierarsenault** [comment]
which sensor are you expecting to see that you don't see

**Comment by marcolivierarsenault** [comment]
```
2024-12-15 13:18:23.638 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up moonraker platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/moonraker/sensor.py", line 308, in async_setup_entry
    await async_setup_optional_sensors(coordinator, entry, async_add_entities)
  File "/config/custom_components/moonraker/sensor.py", line 615, in async_setup_optional_sensors
    async_add_entities([MoonrakerSensor(coordinator, entry, desc) for desc in sensors])
                        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 793, in __init__
    self._attr_native_value = description.value_fn(self)
                              ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/moonraker/sensor.py", line 355, in <lambda>
    value_fn=lambda sensor: round(
                            ~~~~~^
        sensor.coordinator.data["status"][sensor.status_key]["temperature"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        2,
        ^^
    ),
    ^
TypeError: type NoneType doesn't define __round__ method
```

**Comment by marcolivierarsenault** [comment]
I have some code ready to be tested, @paulver10 how comfortable are you to go modify files in your home assistant setup?

if you are can you ssh in your home assistant and replace the entire content of this file


`.../custom_components/moonraker/sensor.py` and put the [content of this file ](https://raw.githubusercontent.com/marcolivierarsenault/moonraker-home-assistant/082d61436b025a6174e789d4ebd523dbedee54d8/custom_components/moonraker/sensor.py)

**Comment by paulver10** [comment]
Hi Marc-Olivier

The new code in sensor.py has done the trick. See screenshots below. I've
also included the debug log again if that is of use to you.

Thank you so much for looking into this so quickly. Do you have a "buy me a
coffee" link or similar so I can send you some money for this awesome
integration and your work with it?

Regards,

**Comment by marcolivierarsenault** [comment]
Thanks, I appreciate  the intent, but no need for more coffee. 

Will push an update to 1.5.1 with the official code in it
