### ISSUE TITLE
Values differ and no camera 

### ISSUE THREAD

**Issue by Kefut** [marcolivierarsenault/moonraker-home-assistant#53]
I really like the idea of having access to Moonraker through HA and the connection in general works like a charm through, but looking into the details, there is something wrong with the values. 
F.e. the camera was not added to HA while I actually have it up and running in klipper, the progress percentage is about 10% lower than in the klipper interface, timing is showing as seconds,...
My setup is a Creality SonicPad running klipper and Home Assistant 2023.3.3

**Comment by delneet** [comment]
> I really like the idea of having access to Moonraker through HA and the connection in general works like a charm through, but looking into the details, there is something wrong with the values. F.e. the camera was not added to HA while I actually have it up and running in klipper, the progress percentage is about 10% lower than in the klipper interface, timing is showing as seconds,... My setup is a Creality SonicPad running klipper and Home Assistant 2023.3.3

I also just bougth the sonic pad.
I have the camera in HA with the mjpeg ip camera integration and an image card.
You can get the camera stream url from within your fluidd webpage settings. If you can't figure it out I'll be happy  to share pics later (on my phone rn).

**Comment by delneet** [comment]
![Screenshot_20230317_111235_Home Assistant](https://user-images.githubusercontent.com/473965/225876504-3637af87-84ec-4ad6-a848-b21b3f8d330b.jpg)
![Screenshot_20230317_111157_Home Assistant](https://user-images.githubusercontent.com/473965/225876511-b4992f8a-f807-4d20-8ba0-306eecfb972f.jpg)
![20230317_110850](https://user-images.githubusercontent.com/473965/225876582-fc35d505-5870-4ed6-9091-e5127f62ea57.jpg)
![20230317_111005](https://user-images.githubusercontent.com/473965/225876591-166485b7-bd3c-485e-b741-697e2acf0724.jpg)

**Comment by marcolivierarsenault** [comment]
I understand that, my concern is I don't want to hardcode it. Currently I am getting the camera URL from https://moonraker.readthedocs.io/en/latest/web_api/#get-webcam-information
Moonraker API directly, and it seams like the Sonic Pad does not offer this data
