### ISSUE TITLE
Add ability to pull data from any temp sensor or fan speed that exists in klipper

### ISSUE THREAD

**Issue by DasBurninator** [marcolivierarsenault/moonraker-home-assistant#54]
## Is your feature request related to a problem? Please describe.

Strictly a feature request for additional sensors being monitored, but I gotta be honest, its gonna be big one that might not be entirely feasible due to possible different naming conventions that can happen in klipper.

I would like to see sensors for other temp sensors and various fan speeds if they exist in the klipper config, regardless of what they are named.

## Describe your setup

Depends on the printer for if they are running a pi or a cb1 or something else. Stack is debian, kiauh for managing the installs, klipper, moonraker, fluidd or mainsail, dealers choice depending on the printer or my mood. Printers are mostly different Vorons and a V400. Typical "I hate enders" deployment.

## Describe the solution you'd like

As stated above, having some additional sensor data coming into home assistant to match what I can do with a simple rest sensor would be nice.

Being that these can have any naming convention and isn't standard like `heater_bed` it can create an interesting problem for implementing this. Maybe grab the list of all enabled heaters per printer and then have it create sensors per entry... Not sure how that would look on the implementation side.

Same concept but for fan speeds as well would be good as well. I'm happy to split this into a separate feature request.

## Additional context

Here is a snippet from the list objects API call from one of my machines to give you an example of the types of objects/sensors I'm looking for. These names could be anything machine to machine, hence the possible challenge with this part.

```
            "fan_generic BedFans",
            "heater_fan filter_fan",
            "heater_fan controller_fan",
            "temperature_sensor enclosure_temp",
            "temperature_sensor frame",
            "temperature_sensor bed_top",
```

**Comment by cashew22** [comment]
Hi @DasBurninator, we just merged a pr #47 that adds the support for those temperature sensors.

It will be part of next release.

I'll try to had the fan sensor as well since it's pretty similar

**Comment by DasBurninator** [comment]
I should have glanced at the closed PRs!
That is great to see getting added in.

**Comment by marcolivierarsenault** [comment]
added in release 0.5.0
