### ISSUE TITLE
More Buttons and Layerinfos

### ISSUE THREAD

**Issue by REDDE4D** [marcolivierarsenault/moonraker-home-assistant#85]
## Is your feature request related to a problem? Please describe.

No

## Describe your setup

RPi 4 with Moonraker + Mainsail
Anycubic Vyper with Klipper

## Describe the solution you'd like

It would be nice to have Buttons for:
Klipper Control:
 - Restart
 - Firmware Restart

Print Control:
 - Pause
 - Resume
 - Cancel

Host Control:
 - Restart

Layer Infos (If possible):
 - Current Layer
 - Total Layers

**Comment by cashew22** [comment]
- [ ] Add Klipper restart
- [ ] Add Klipper Firmware restart
- [ ] Add print pause
- [ ] Add print resume
- [ ] Add print cancel
- [ ] Add Host restart
- [ ] Add the current layer
- [ ] Add total layers

**Comment by cashew22** [comment]
I guess we can add some of them in 0.7.0
