### ISSUE TITLE
[Feature request] Power APIs

### ISSUE THREAD

**Issue by seebaer1976** [marcolivierarsenault/moonraker-home-assistant#86]
first of all thank you for your work

would it be possible to add the Power APIs?
so that you can switch self-created switches, in moonraker, via home assistant and even some automations.

[https://moonraker.readthedocs.io/en/latest/web_api/#get-device-list](https://moonraker.readthedocs.io/en/latest/web_api/#get-device-list)
[https://moonraker.readthedocs.io/en/latest/configuration/#power](https://moonraker.readthedocs.io/en/latest/configuration/#power)

**Comment by marcolivierarsenault** [comment]
we will look at this
