### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by Jonisos** [marcolivierarsenault/moonraker-home-assistant#87]
Hey!
I'm just getting started with HA so I'm kinda lost on how to proceed. 

I installed the Plugin via HACS and did multiple reboots of HA and the whole system but as far as I understood there should be some button in "Devices & Services" but there is nothing for me. I already read all Issues and the Wiki but didn't find any example config.

Is there anything I have to add to my configuration.yaml? I also tried to include "custom_components: !include_dir_named custom_components" but this doesn't work..

Thanks for the Plugin though. I was very happy to find it!

**Comment by marcolivierarsenault** [comment]
once it is installed via HACS, you can load it like a normal integration. 
![image](https://user-images.githubusercontent.com/2634090/229232703-ebbe8df2-d3bd-4c76-9816-03ea1a361524.png)

**Comment by Jonisos** [comment]
Perfect, that worked! Thank you
