### ISSUE TITLE
[Sonic Pad] Error connecting 

### ISSUE THREAD

**Issue by Earlmac84** [marcolivierarsenault/moonraker-home-assistant#92]
When trying to connect to printer with ip address at set up, moonraker returned with "error connecting to" 

Address I'm using is http://192.168.1.5 with standard port 7125 and set up all on sonic pad.

Help?

**Comment by marcolivierarsenault** [comment]
- can you try removing the `http://` and go straight with the IP.
- Can you validate that you can access the API vi http

**Comment by Earlmac84** [comment]
Thanks for swift reply.

1. Yes, tried IP. Error below
2. Yes I can access the console via http, no problem.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/moonraker/api.py:32
Integration: Moonraker (documentation, issues)
First occurred: April 2, 2023 at 11:09:25 PM (3 occurrences)
Last logged: 7:37:16 AM

Error setting up entry moonraker for moonraker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/moonraker/__init__.py", line 55, in async_setup_entry
    await api.start()
  File "/config/custom_components/moonraker/api.py", line 32, in start
    return await self.client.connect()
  File "/usr/local/lib/python3.10/site-packages/moonraker_api/websockets/websocketclient.py", line 346, in connect
    await asyncio.wait_for(conn_event, self._timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 432, in wait_for
    await waiter
asyncio.exceptions.CancelledError

**Comment by marcolivierarsenault** [comment]
can you send a copy of your moonraker config and a screenshot of HA configuration popup for moonraker (where you enter the ip and port)

**Comment by marcolivierarsenault** [comment]
Also, can you login ssh on your HA and ping your printer to make sure you have connectivity FROM HA

**Comment by Earlmac84** [comment]
No problem. see attached. 
![MR Cap](https://user-images.githubusercontent.com/129697469/229895246-b301e93c-5476-4626-a434-80a82aa305ce.JPG)
[MR.txt](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/11152182/MR.txt)

**Comment by marcolivierarsenault** [comment]
can you send a copy of the printers logs: 
/mnt/UDISK/printer_logs

Make sure it capture a time frame where you were attempting to connect.

**Comment by marcolivierarsenault** [comment]
Looks like it is expecting a login:

```
[authorization]
force_logins: True
cors_domains:
  *.local
  *.lan
  *://app.fluidd.xyz

trusted_clients:
  10.0.0.0/8
  127.0.0.0/8
  169.254.0.0/16
  172.16.0.0/12
  192.168.0.0/16
  FE80::/10
  ::1/128
  ```

**Comment by Earlmac84** [comment]
Sure, currently running a print so will Putty to it once its done. few hours. 
thanks again

**Comment by Earlmac84** [comment]
Attached. 
[moonraker.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/11159507/moonraker.log)
[qt.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/11159508/qt.log)
[klippy.log](https://github.com/marcolivierarsenault/moonraker-home-assistant/files/11159509/klippy.log)

**Comment by marcolivierarsenault** [comment]
@Earlmac84 do you have a login (username/password) to connect to mainsail web page?

Can you try to change your moonraker config 
```
authorization]
force_logins: True
```

to False, restart your printer and test again. 



Have you try to ping your printer from your HA container or host?

**Comment by cashew22** [comment]
If the proposed action of @marcolivierarsenault is succesful, I suggest to use an api key for your home assistant

**Comment by marcolivierarsenault** [comment]
@Earlmac84 Any progress?

**Comment by Earlmac84** [comment]
Sorry guys was away with work. No dice with the FALSE config change.
Ping returns packet

**Comment by sangdrax8** [comment]
I am probably in a similar setup, I am looking to connect to my sonicpad, and getting no luck so far.  I still need to pull debug logs etc, but I do have my Cura connected so I have seen other applications use the API with some success.

**Comment by marcolivierarsenault** [comment]
@sangdrax8 we do have couple of issue with SonicPad, but we don't own any so hard to fix. Would love someone that owns one with help with those fixes

**Comment by sangdrax8** [comment]
I wouldn't mind helping, but I haven't touched my home assistant since setup a few years ago.  Might take me a minute to recall how to get logs etc from it.  Although it looked like this post already had debug logs?  What could I assist with?

**Comment by gugamc** [comment]
Same problem with Sonic Pad.

**Comment by MattiaConfalonieri** [comment]
HI, i am new, NO problem gere to Sonic Pad Connection, can I help?

**Comment by Sunshinepl84** [comment]
i have some problems with the SP maybe you can help me to intigrate it to my HA @MattiaConfalonieri

**Comment by Coldness00** [comment]
Hello,
On my side no issue to connect, but it looks like it trigger at some point bugs with the Pad as I loose MCU communication with the printer (Error Key 1 and 298)
SInce I removed the Integration, no more issue.
I'm kind of sad because the integration is really amazing.

**Comment by Coldness00** [comment]
> @sangdrax8 we do have couple of issue with SonicPad, but we don't own any so hard to fix. Would love someone that owns one with help with those fixes

Hello,
How could I support you?

**Comment by marcolivierarsenault** [comment]
Hi @Coldness00, 
Looks like there are a bunch of errors with the integration when using SonicPad, I am looking for someone that can trouble shoot it and fix the code.

**Comment by Coldness00** [comment]
Dear @marcolivierarsenault 
Unfortunately, I do not know enough to support on coding.
However, if you want to guide me through tests or logs or anything to support you on this matter I might help.

**Comment by marcolivierarsenault** [comment]
@Coldness00 @MattiaConfalonieri @Earlmac84 

We added some more debuging logs. 

Could you download the latest `main` version. Make sure to `Update information` before re-downloading 
follow steps [here](https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html) 

then you can send me a debug log. Details [here](https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log)

**Comment by jn3va** [comment]
Does the SonicPad have a moonraker.conf that you can check/edit?    I don;t have a SonicPad, but on my Elegoo it's moonraker.conf was set to host: localhost.  This seems to limit all moonraker API connections to just accepting connections from the IP of the printer.   I changed it to 0.0.0.0 and rebooted the printer and was then able to connect to the API from a different IP.  This allowed me to access the api from my desktop's web browser (http://192.168.1.111:7125) as well as get the moonraker HA integration to connect.

**Comment by fbloemhof** [comment]
I just installed the component and configured it to my Sonic Pad (with no customizations) and it works like a charm.
